// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type AfhandelingsItemCreateRequest = {
    domein?: string | null;
    entityId?: string | null;
    label?: string | null;
    notitie?: string | null;
};

export type AfhandelingsItemDto = {
    id?: string;
    domein?: string | null;
    entityId?: string | null;
    label?: string | null;
    status?: string | null;
    notitie?: string | null;
    afgehandeldOp?: string | null;
    aangemaaktOp?: string;
    gewijzigdOp?: string;
};

export type AfhandelingsItemUpdateRequest = {
    status?: string | null;
    notitie?: string | null;
};

export type AuditLogCreateDto = {
    actie?: string | null;
    entityType?: string | null;
    entityId?: string | null;
    details?: string | null;
};

export type AuditLogDto = {
    id?: string;
    tijdstip?: string;
    actie?: string | null;
    entityType?: string | null;
    entityId?: string | null;
    details?: string | null;
};

export type AuditLogPagedResult = {
    items?: Array<AuditLogDto> | null;
    heeftMeer?: boolean;
};

export type BankrekeningResponse = {
    id?: string;
    bankNaam?: string | null;
    iban?: string | null;
    rekeningType?: string | null;
    saldo?: number | null;
    vermogensSoort?: VermogensSoort;
    notities?: string | null;
};

export type BankrekeningUpsertRequest = {
    bankNaam?: string | null;
    iban?: string | null;
    rekeningType?: string | null;
    saldo?: number | null;
    vermogensSoort?: VermogensSoort;
    notities?: string | null;
};

export type BegunstigdeResponse = {
    id?: string;
    naam?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    omschrijving?: string | null;
    percentage?: number | null;
    isLegitiemePortie?: boolean;
    erfgenaamId?: string | null;
    noodcontactId?: string | null;
};

export type BegunstigdeUpsertRequest = {
    naam?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    omschrijving?: string | null;
    percentage?: number | null;
    isLegitiemePortie?: boolean;
    erfgenaamId?: string | null;
    noodcontactId?: string | null;
};

export type BezitSchuldSummary = {
    id?: string;
    schuldeiser?: string | null;
    type?: string | null;
    bedrag?: number;
    maandelijkseAflossing?: number | null;
    leaseMaatschappij?: string | null;
    rentepercentage?: number | null;
    einddatum?: string | null;
};

export type BezitSchuldUpsertRequest = {
    schuldeiser?: string | null;
    type?: string | null;
    bedrag?: number;
    maandelijkseAflossing?: number | null;
    leaseMaatschappij?: string | null;
    rentepercentage?: number | null;
    einddatum?: string | null;
};

export type BurgerlijkeStaat = 0 | 1 | 2 | 3 | 4;

export type CeremonieDetailResponse = {
    id?: string;
    onderdeel?: string | null;
    beschrijving?: string | null;
    volgorde?: number;
    muziek?: string | null;
    spreker?: string | null;
    tekstlezing?: string | null;
    dresscode?: string | null;
};

export type CeremonieDetailUpsertRequest = {
    onderdeel?: string | null;
    beschrijving?: string | null;
    volgorde?: number;
    muziek?: string | null;
    spreker?: string | null;
    tekstlezing?: string | null;
    dresscode?: string | null;
};

export type CreateProfileRequest = {
    naam?: string | null;
    relatie?: string | null;
};

export type CryptoWalletOntsluitelResponse = {
    id?: string;
    walletNaam?: string | null;
    cryptoType?: string | null;
    seedPhrase?: string | null;
    walletAdres?: string | null;
};

export type CryptoWalletResponse = {
    id?: string;
    walletNaam?: string | null;
    cryptoType?: string | null;
    walletAdres?: string | null;
    exchange?: string | null;
    notities?: string | null;
};

export type CryptoWalletUpsertRequest = {
    walletNaam?: string | null;
    cryptoType?: string | null;
    walletAdres?: string | null;
    seedPhrase?: string | null;
    exchange?: string | null;
    notities?: string | null;
};

export type DigitaalAccountResponse = {
    id?: string;
    platformNaam?: string | null;
    categorie?: string | null;
    gebruikersnaam?: string | null;
    emailAdres?: string | null;
    url?: string | null;
    gewensteActie?: string | null;
    overdrachtAan?: string | null;
    notities?: string | null;
};

export type DigitaalAccountUpsertRequest = {
    platformNaam?: string | null;
    categorie?: string | null;
    gebruikersnaam?: string | null;
    emailAdres?: string | null;
    url?: string | null;
    gewensteActie?: string | null;
    overdrachtAan?: string | null;
    notities?: string | null;
};

export type DocumentResponse = {
    id?: string;
    naam?: string | null;
    categorie?: string | null;
    bestandsNaam?: string | null;
    contentType?: string | null;
    bestandsGrootte?: number;
    notities?: string | null;
    verlooptOp?: string | null;
    aangemaaktOp?: string;
    gewijzigdOp?: string;
    documentGroepId?: string;
    versie?: number;
    aantalVersies?: number;
};

export type DocumentUpdateRequest = {
    verlooptOp?: string | null;
    notities?: string | null;
};

export type DocumentVersieResponse = {
    id?: string;
    versie?: number;
    bestandsNaam?: string | null;
    bestandsGrootte?: number;
    aangemaaktOp?: string;
};

export type DonorRegistratieResponse = {
    id?: string;
    eigenaarId?: string;
    keuze?: string | null;
    isGeregistreerdBijDonorregister?: boolean;
    donorregisterReferentie?: string | null;
    toelichting?: string | null;
    beslisserNaam?: string | null;
    beslisserRelatie?: string | null;
    beslisserTelefoon?: string | null;
    aangemaaktOp?: string;
    gewijzigdOp?: string;
    orgaanKeuzes?: Array<OrgaanKeuzeResponse> | null;
};

export type DonorRegistratieUpsertRequest = {
    keuze?: string | null;
    isGeregistreerdBijDonorregister?: boolean;
    donorregisterReferentie?: string | null;
    toelichting?: string | null;
    beslisserNaam?: string | null;
    beslisserRelatie?: string | null;
    beslisserTelefoon?: string | null;
};

export type EigenaarResponse = {
    id?: string;
    voornaam?: string | null;
    achternaam?: string | null;
    tussenvoegsel?: string | null;
    geboortedatum?: string;
    bsn?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    telefoon?: string | null;
    email?: string | null;
    notaris?: string | null;
    notarisKantoor?: string | null;
    notarisTelefoon?: string | null;
    notarisEmail?: string | null;
    notarisAdres?: string | null;
    notarisPostcode?: string | null;
    notarisPlaats?: string | null;
    burgerlijkeStaat?: BurgerlijkeStaat;
    huwelijksVoorwaarden?: HuwelijksVoorwaarden;
    datumHuwelijk?: string | null;
    legitimatieSoort?: LegitimatieSoort;
    legitimatieNummer?: string | null;
    legitimatieDatumAfgifte?: string | null;
    legitimatieGeldigTot?: string | null;
    heeftProfielFoto?: boolean;
    aangemaaktOp?: string;
    gewijzigdOp?: string;
};

export type EigenaarUpsertRequest = {
    voornaam?: string | null;
    achternaam?: string | null;
    tussenvoegsel?: string | null;
    geboortedatum?: string;
    bsn?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    telefoon?: string | null;
    email?: string | null;
    notaris?: string | null;
    notarisKantoor?: string | null;
    notarisTelefoon?: string | null;
    notarisEmail?: string | null;
    notarisAdres?: string | null;
    notarisPostcode?: string | null;
    notarisPlaats?: string | null;
    burgerlijkeStaat?: BurgerlijkeStaat;
    huwelijksVoorwaarden?: HuwelijksVoorwaarden;
    datumHuwelijk?: string | null;
    legitimatieSoort?: LegitimatieSoort;
    legitimatieNummer?: string | null;
    legitimatieDatumAfgifte?: string | null;
    legitimatieGeldigTot?: string | null;
};

export type EncryptedBackupRequest = {
    password?: string | null;
};

export type ErfgenaamResponse = {
    id?: string;
    voornaam?: string | null;
    achternaam?: string | null;
    tussenvoegsel?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    geboortedatum?: string | null;
    bsn?: string | null;
    shareIndex?: number | null;
    heeftShareOntvangen?: boolean;
    shareUitgegevenOp?: string | null;
    legitimatieSoort?: LegitimatieSoort;
    legitimatieNummer?: string | null;
    legitimatieDatumAfgifte?: string | null;
    legitimatieGeldigTot?: string | null;
};

export type ErfgenaamToewijzingResponse = {
    id?: string;
    erfgenaamId?: string;
    erfgenaamNaam?: string | null;
    entityType?: string | null;
    entityId?: string;
    entityNaam?: string | null;
    instructies?: string | null;
};

export type ErfgenaamToewijzingUpsertRequest = {
    erfgenaamId?: string;
    entityType?: string | null;
    entityId?: string;
    instructies?: string | null;
};

export type ErfgenaamUpsertRequest = {
    voornaam?: string | null;
    achternaam?: string | null;
    tussenvoegsel?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    geboortedatum?: string | null;
    bsn?: string | null;
    legitimatieSoort?: LegitimatieSoort;
    legitimatieNummer?: string | null;
    legitimatieDatumAfgifte?: string | null;
    legitimatieGeldigTot?: string | null;
};

export type ExecuteurResponse = {
    id?: string;
    naam?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    bevoegdheden?: string | null;
    erfgenaamId?: string | null;
    noodcontactId?: string | null;
};

export type ExecuteurUpsertRequest = {
    naam?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    bevoegdheden?: string | null;
    erfgenaamId?: string | null;
    noodcontactId?: string | null;
};

export type FysiekBezitResponse = {
    id?: string;
    categorie?: string | null;
    omschrijving?: string | null;
    geschatteWaarde?: number | null;
    locatie?: string | null;
    bestemdeErfgenaamId?: string | null;
    bestemdeErfgenaamNaam?: string | null;
    vermogensSoort?: VermogensSoort;
    notities?: string | null;
    kadastraalNummer?: string | null;
    kenteken?: string | null;
    kvKNummer?: string | null;
    linkedSchulden?: Array<BezitSchuldSummary> | null;
};

export type FysiekBezitUpsertRequest = {
    categorie?: string | null;
    omschrijving?: string | null;
    geschatteWaarde?: number | null;
    locatie?: string | null;
    bestemdeErfgenaamId?: string | null;
    vermogensSoort?: VermogensSoort;
    notities?: string | null;
    kadastraalNummer?: string | null;
    kenteken?: string | null;
    kvKNummer?: string | null;
};

export type GedeeldNoodcontactDto = {
    naam?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    rol?: string | null;
    instructies?: string | null;
};

export type GenereerSharesRequest = {
    wachtwoord?: string | null;
    aantalDelen?: number;
    drempel?: number;
};

export type GenereerSharesResponse = {
    delen?: Array<ShareInfo> | null;
    drempel?: number;
    totaalAantalDelen?: number;
};

export type HuwelijksVoorwaarden = 0 | 1 | 2 | 3;

export type LegitimairePortieCheckResult = {
    heeftWaarschuwing?: boolean;
    aantalKinderen?: number;
    heeftPartner?: boolean;
    minimumPercentagePerKind?: number;
    waarschuwingen?: Array<LegitimairePortieWaarschuwing> | null;
};

export type LegitimairePortieWaarschuwing = {
    naam?: string | null;
    toegewezenPercentage?: number | null;
    minimumPercentage?: number;
};

export type LegitimatieSoort = 0 | 1 | 2 | 3;

export type NoodcontactResponse = {
    id?: string;
    naam?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    rol?: string | null;
    instructies?: string | null;
    bedrijfsNaam?: string | null;
    functie?: string | null;
    prioriteit?: number;
    isGedeeld?: boolean;
};

export type NoodcontactUpsertRequest = {
    naam?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    rol?: string | null;
    instructies?: string | null;
    bedrijfsNaam?: string | null;
    functie?: string | null;
    prioriteit?: number;
    isGedeeld?: boolean;
};

export type OntgrendelErfgenaamRequest = {
    shares?: Array<string> | null;
};

export type OntgrendelRequest = {
    wachtwoord?: string | null;
};

export type OntvangerResponse = {
    id?: string;
    erfgenaamId?: string;
    naam?: string | null;
};

export type OrgaanKeuzeResponse = {
    id?: string;
    orgaan?: string | null;
    welDoneren?: boolean;
    toelichting?: string | null;
};

export type OrgaanKeuzeUpsertRequest = {
    orgaan?: string | null;
    welDoneren?: boolean;
    toelichting?: string | null;
};

export type ProfileResponse = {
    id?: string;
    naam?: string | null;
    relatie?: string | null;
    isPrimair?: boolean;
    aangemaaktOp?: string;
    fotoThumbnail?: string | null;
};

export type ReconstrueerRequest = {
    delen?: Array<string> | null;
};

export type SchuldResponse = {
    id?: string;
    schuldeiser?: string | null;
    schuldeiserTelefoon?: string | null;
    schuldeiserEmail?: string | null;
    type?: string | null;
    bedrag?: number;
    maandelijkseAflossing?: number | null;
    referentie?: string | null;
    vermogensSoort?: VermogensSoort;
    notities?: string | null;
    hypotheekVorm?: string | null;
    rentepercentage?: number | null;
    maandelijkseRente?: number | null;
    einddatum?: string | null;
    restschuld?: number | null;
    leaseMaatschappij?: string | null;
    bezitId?: string | null;
    bezitNaam?: string | null;
};

export type SchuldUpsertRequest = {
    schuldeiser?: string | null;
    schuldeiserTelefoon?: string | null;
    schuldeiserEmail?: string | null;
    type?: string | null;
    bedrag?: number;
    maandelijkseAflossing?: number | null;
    referentie?: string | null;
    vermogensSoort?: VermogensSoort;
    notities?: string | null;
    hypotheekVorm?: string | null;
    rentepercentage?: number | null;
    maandelijkseRente?: number | null;
    einddatum?: string | null;
    restschuld?: number | null;
};

export type SectieNotitieResponse = {
    id?: string;
    sectie?: string | null;
    inhoud?: string | null;
    gewijzigdOp?: string;
};

export type SectieNotitieUpsertRequest = {
    inhoud?: string | null;
};

export type SelectProfileRequest = {
    profielId?: string;
};

export type SetupRequest = {
    wachtwoord?: string | null;
};

export type ShareInfo = {
    index?: number;
    waarde?: string | null;
};

export type TestamentInfoResponse = {
    id?: string;
    eigenaarId?: string;
    testamentType?: string | null;
    notarisNaam?: string | null;
    notarisKantoor?: string | null;
    notarisTelefoon?: string | null;
    notarisEmail?: string | null;
    notarisAdres?: string | null;
    notarisPostcode?: string | null;
    notarisPlaats?: string | null;
    datumTestament?: string | null;
    testamentLocatie?: string | null;
    ctR_Nummer?: string | null;
    algemeneWensen?: string | null;
    bijzondereBepalingen?: string | null;
    uitsluitingsClausule?: boolean | null;
    legaten?: string | null;
    aangemaaktOp?: string;
    gewijzigdOp?: string;
};

export type TestamentInfoUpsertRequest = {
    testamentType?: string | null;
    notarisNaam?: string | null;
    notarisKantoor?: string | null;
    notarisTelefoon?: string | null;
    notarisEmail?: string | null;
    notarisAdres?: string | null;
    notarisPostcode?: string | null;
    notarisPlaats?: string | null;
    datumTestament?: string | null;
    testamentLocatie?: string | null;
    ctR_Nummer?: string | null;
    algemeneWensen?: string | null;
    bijzondereBepalingen?: string | null;
    uitsluitingsClausule?: boolean | null;
    legaten?: string | null;
};

export type TestamentSnapshotCreateRequest = {
    notitie?: string | null;
};

export type TestamentSnapshotDetailResponse = {
    id?: string;
    versie?: number;
    snapshotDatum?: string;
    notitie?: string | null;
    snapshotJson?: string | null;
};

export type TestamentSnapshotResponse = {
    id?: string;
    versie?: number;
    snapshotDatum?: string;
    notitie?: string | null;
};

export type TestamentVergelijkingResponse = {
    versie1?: TestamentSnapshotDetailResponse;
    versie2?: TestamentSnapshotDetailResponse;
    verschillen?: Array<TestamentVerschil> | null;
};

export type TestamentVerschil = {
    veld?: string | null;
    waardeVersie1?: string | null;
    waardeVersie2?: string | null;
};

export type UitvaartGenodigdeResponse = {
    id?: string;
    naam?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    notities?: string | null;
    erfgenaamId?: string | null;
    noodcontactId?: string | null;
};

export type UitvaartGenodigdeUpsertRequest = {
    naam?: string | null;
    relatie?: string | null;
    telefoon?: string | null;
    email?: string | null;
    adres?: string | null;
    postcode?: string | null;
    woonplaats?: string | null;
    notities?: string | null;
    erfgenaamId?: string | null;
    noodcontactId?: string | null;
};

export type UitvaartWensenResponse = {
    id?: string;
    eigenaarId?: string;
    voorkeurType?: string | null;
    begraafplaats?: string | null;
    uitvaartOndernemer?: string | null;
    uitvaartOndernemerTelefoon?: string | null;
    uitvaartOndernemerEmail?: string | null;
    uitvaartOndernemerAdres?: string | null;
    uitvaartOndernemerPostcode?: string | null;
    uitvaartOndernemerPlaats?: string | null;
    heeftUitvaartVerzekering?: boolean;
    uitvaartVerzekeringDetails?: string | null;
    ceremonieSoort?: string | null;
    ceremonieLocatie?: string | null;
    muziekwensen?: string | null;
    sprekers?: string | null;
    bloemen?: string | null;
    kledingwensen?: string | null;
    rouwkaartTekst?: string | null;
    rouwadvertentieTekst?: string | null;
    condoleance?: string | null;
    overigeWensen?: string | null;
    voorkeurBegraafplaatsNaam?: string | null;
    voorkeurBegraafplaatsAdres?: string | null;
    voorkeurCrematoriumnaam?: string | null;
    voorkeurCrematoriumAdres?: string | null;
    voorkeurAulaNaam?: string | null;
    voorkeurAulaAdres?: string | null;
    budgetRichting?: string | null;
    datumOpgesteld?: string | null;
    aangemaaktOp?: string;
    gewijzigdOp?: string;
};

export type UitvaartWensenUpsertRequest = {
    voorkeurType?: string | null;
    begraafplaats?: string | null;
    uitvaartOndernemer?: string | null;
    uitvaartOndernemerTelefoon?: string | null;
    uitvaartOndernemerEmail?: string | null;
    uitvaartOndernemerAdres?: string | null;
    uitvaartOndernemerPostcode?: string | null;
    uitvaartOndernemerPlaats?: string | null;
    heeftUitvaartVerzekering?: boolean;
    uitvaartVerzekeringDetails?: string | null;
    ceremonieSoort?: string | null;
    ceremonieLocatie?: string | null;
    muziekwensen?: string | null;
    sprekers?: string | null;
    bloemen?: string | null;
    kledingwensen?: string | null;
    rouwkaartTekst?: string | null;
    rouwadvertentieTekst?: string | null;
    condoleance?: string | null;
    overigeWensen?: string | null;
    voorkeurBegraafplaatsNaam?: string | null;
    voorkeurBegraafplaatsAdres?: string | null;
    voorkeurCrematoriumnaam?: string | null;
    voorkeurCrematoriumAdres?: string | null;
    voorkeurAulaNaam?: string | null;
    voorkeurAulaAdres?: string | null;
    budgetRichting?: string | null;
    datumOpgesteld?: string | null;
};

export type VermogensSoort = 0 | 1;

export type VerzekeringResponse = {
    id?: string;
    verzekeraar?: string | null;
    verzekeraarTelefoon?: string | null;
    verzekeraarEmail?: string | null;
    polisNummer?: string | null;
    type?: string | null;
    verzekerdBedrag?: number | null;
    begunstigde?: string | null;
    begunstigdeErfgenaamId?: string | null;
    vermogensSoort?: VermogensSoort;
    notities?: string | null;
};

export type VerzekeringUpsertRequest = {
    verzekeraar?: string | null;
    verzekeraarTelefoon?: string | null;
    verzekeraarEmail?: string | null;
    polisNummer?: string | null;
    type?: string | null;
    verzekerdBedrag?: number | null;
    begunstigde?: string | null;
    begunstigdeErfgenaamId?: string | null;
    vermogensSoort?: VermogensSoort;
    notities?: string | null;
};

export type VideoboodschapResponse = {
    id?: string;
    titel?: string | null;
    beschrijving?: string | null;
    bestandsNaam?: string | null;
    contentType?: string | null;
    bestandsGrootte?: number;
    duurSeconden?: number | null;
    ontvangers?: Array<OntvangerResponse> | null;
    aangemaaktOp?: string;
    gewijzigdOp?: string;
};

export type VideoboodschapUpdateRequest = {
    titel?: string | null;
    beschrijving?: string | null;
    ontvangerIds?: Array<string> | null;
};

export type VoorwaardeResponse = {
    id?: string;
    voorwaarde?: string | null;
    toelichting?: string | null;
};

export type VoorwaardeUpsertRequest = {
    voorwaarde?: string | null;
    toelichting?: string | null;
};

export type WachtwoordEntryCreateRequest = {
    naam?: string | null;
    gebruikersnaam?: string | null;
    wachtwoord?: string | null;
    url?: string | null;
    notities?: string | null;
};

export type WachtwoordEntryResponse = {
    id?: string;
    naam?: string | null;
    gebruikersnaam?: string | null;
    url?: string | null;
    notities?: string | null;
    hasPassword?: boolean;
};

export type WachtwoordEntryUpdateRequest = {
    naam?: string | null;
    gebruikersnaam?: string | null;
    nieuwWachtwoord?: string | null;
    url?: string | null;
    notities?: string | null;
};

export type WachtwoordOntsluitelResponse = {
    id?: string;
    naam?: string | null;
    gebruikersnaam?: string | null;
    wachtwoord?: string | null;
    url?: string | null;
    notities?: string | null;
};

export type WachtwoordWijzigenRequest = {
    huidigWachtwoord?: string | null;
    nieuwWachtwoord?: string | null;
};

export type WerkgeverResponse = {
    id?: string;
    bedrijfsNaam?: string | null;
    kvKNummer?: string | null;
    adres?: string | null;
    postcode?: string | null;
    vestigingsplaats?: string | null;
    website?: string | null;
    telefoonHoofdkantoor?: string | null;
    functietitel?: string | null;
    afdeling?: string | null;
    startdatumDienstverband?: string | null;
    isZzp?: boolean;
    pensioenfondNaam?: string | null;
    pensioenfondTelefoon?: string | null;
    pensioenfondEmail?: string | null;
    hrContactNaam?: string | null;
    hrContactTelefoon?: string | null;
    hrContactEmail?: string | null;
    leidinggevendeNaam?: string | null;
    leidinggevendeTelefoon?: string | null;
    leidinggevendeEmail?: string | null;
    notities?: string | null;
};

export type WerkgeverUpsertRequest = {
    bedrijfsNaam?: string | null;
    kvKNummer?: string | null;
    adres?: string | null;
    postcode?: string | null;
    vestigingsplaats?: string | null;
    website?: string | null;
    telefoonHoofdkantoor?: string | null;
    functietitel?: string | null;
    afdeling?: string | null;
    startdatumDienstverband?: string | null;
    isZzp?: boolean;
    pensioenfondNaam?: string | null;
    pensioenfondTelefoon?: string | null;
    pensioenfondEmail?: string | null;
    hrContactNaam?: string | null;
    hrContactTelefoon?: string | null;
    hrContactEmail?: string | null;
    leidinggevendeNaam?: string | null;
    leidinggevendeTelefoon?: string | null;
    leidinggevendeEmail?: string | null;
    notities?: string | null;
};

export type WilsverklaringResponse = {
    id?: string;
    eigenaarId?: string;
    datumOndertekening?: string | null;
    wilEuthanasie?: boolean;
    situatieBeschrijving?: string | null;
    huisarts?: string | null;
    huisartsPraktijk?: string | null;
    huisartsTelefoon?: string | null;
    huisartsEmail?: string | null;
    vertegenwoordigerNaam?: string | null;
    vertegenwoordigerRelatie?: string | null;
    vertegenwoordigerTelefoon?: string | null;
    vertegenwoordigerEmail?: string | null;
    vertegenwoordigerAdres?: string | null;
    vertegenwoordigerPostcode?: string | null;
    vertegenwoordigerWoonplaats?: string | null;
    aanvullendeWensen?: string | null;
    dementieClausule?: boolean;
    dementieClausuleToelichting?: string | null;
    behandelVerbod?: string | null;
    vertegenwoordiger2Naam?: string | null;
    vertegenwoordiger2Relatie?: string | null;
    vertegenwoordiger2Telefoon?: string | null;
    vertegenwoordiger2Email?: string | null;
    situatieOpties?: string | null;
    situatieNotitie?: string | null;
    aangemaaktOp?: string;
    gewijzigdOp?: string;
};

export type WilsverklaringUpsertRequest = {
    datumOndertekening?: string | null;
    wilEuthanasie?: boolean;
    situatieBeschrijving?: string | null;
    huisarts?: string | null;
    huisartsPraktijk?: string | null;
    huisartsTelefoon?: string | null;
    huisartsEmail?: string | null;
    vertegenwoordigerNaam?: string | null;
    vertegenwoordigerRelatie?: string | null;
    vertegenwoordigerTelefoon?: string | null;
    vertegenwoordigerEmail?: string | null;
    vertegenwoordigerAdres?: string | null;
    vertegenwoordigerPostcode?: string | null;
    vertegenwoordigerWoonplaats?: string | null;
    aanvullendeWensen?: string | null;
    dementieClausule?: boolean;
    dementieClausuleToelichting?: string | null;
    behandelVerbod?: string | null;
    vertegenwoordiger2Naam?: string | null;
    vertegenwoordiger2Relatie?: string | null;
    vertegenwoordiger2Telefoon?: string | null;
    vertegenwoordiger2Email?: string | null;
    situatieOpties?: string | null;
    situatieNotitie?: string | null;
};

export type ZoekItem = {
    id?: string;
    titel?: string | null;
    type?: string | null;
    beschrijving?: string | null;
    link?: string | null;
};

export type ZoekResultaat = {
    erfgenamen?: Array<ZoekItem> | null;
    noodcontacten?: Array<ZoekItem> | null;
    digitaleAccounts?: Array<ZoekItem> | null;
    wachtwoorden?: Array<ZoekItem> | null;
    cryptoWallets?: Array<ZoekItem> | null;
    bezittingen?: Array<ZoekItem> | null;
    bankrekeningen?: Array<ZoekItem> | null;
    verzekeringen?: Array<ZoekItem> | null;
    schulden?: Array<ZoekItem> | null;
    documenten?: Array<ZoekItem> | null;
};

export type GetApiV1AfhandelingData = {
    body?: never;
    path?: never;
    query?: {
        domein?: string;
    };
    url: '/api/v1/afhandeling';
};

export type GetApiV1AfhandelingResponses = {
    /**
     * OK
     */
    200: Array<AfhandelingsItemDto>;
};

export type GetApiV1AfhandelingResponse = GetApiV1AfhandelingResponses[keyof GetApiV1AfhandelingResponses];

export type PostApiV1AfhandelingData = {
    body?: AfhandelingsItemCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/afhandeling';
};

export type PostApiV1AfhandelingResponses = {
    /**
     * OK
     */
    200: AfhandelingsItemDto;
};

export type PostApiV1AfhandelingResponse = PostApiV1AfhandelingResponses[keyof PostApiV1AfhandelingResponses];

export type GetApiV1AfhandelingSamenvattingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/afhandeling/samenvatting';
};

export type GetApiV1AfhandelingSamenvattingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1AfhandelingByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/afhandeling/{id}';
};

export type DeleteApiV1AfhandelingByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1AfhandelingByIdData = {
    body?: AfhandelingsItemUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/afhandeling/{id}';
};

export type PutApiV1AfhandelingByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AfhandelingInitialiseerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/afhandeling/initialiseer';
};

export type PostApiV1AfhandelingInitialiseerResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1AuditLogData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        actie?: string;
        entityType?: string;
        from?: string;
        to?: string;
        before?: string;
    };
    url: '/api/v1/audit-log';
};

export type GetApiV1AuditLogResponses = {
    /**
     * OK
     */
    200: AuditLogPagedResult;
};

export type GetApiV1AuditLogResponse = GetApiV1AuditLogResponses[keyof GetApiV1AuditLogResponses];

export type PostApiV1AuditLogData = {
    body?: AuditLogCreateDto;
    path?: never;
    query?: never;
    url: '/api/v1/audit-log';
};

export type PostApiV1AuditLogResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1AuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/status';
};

export type GetApiV1AuthStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthOntgrendelData = {
    body?: OntgrendelRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/ontgrendel';
};

export type PostApiV1AuthOntgrendelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthVergrendelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/vergrendel';
};

export type PostApiV1AuthVergrendelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthWachtwoordData = {
    body?: WachtwoordWijzigenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/wachtwoord';
};

export type PostApiV1AuthWachtwoordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1AuthAccountData = {
    body?: OntgrendelRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/account';
};

export type DeleteApiV1AuthAccountResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthOntgrendelErfgenaamData = {
    body?: OntgrendelErfgenaamRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/ontgrendel-erfgenaam';
};

export type PostApiV1AuthOntgrendelErfgenaamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthSelecteerProfielData = {
    body?: SelectProfileRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/selecteer-profiel';
};

export type PostApiV1AuthSelecteerProfielResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthSetupData = {
    body?: SetupRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/setup';
};

export type PostApiV1AuthSetupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1BackupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/backup';
};

export type GetApiV1BackupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1BackupRestoreData = {
    body?: {
        Wachtwoord: string;
        Bestand: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/backup/restore';
};

export type PostApiV1BackupRestoreResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1BoedelSamenvattingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/boedel/samenvatting';
};

export type GetApiV1BoedelSamenvattingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1BoedelBezittingenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/boedel/bezittingen';
};

export type GetApiV1BoedelBezittingenResponses = {
    /**
     * OK
     */
    200: Array<FysiekBezitResponse>;
};

export type GetApiV1BoedelBezittingenResponse = GetApiV1BoedelBezittingenResponses[keyof GetApiV1BoedelBezittingenResponses];

export type PostApiV1BoedelBezittingenData = {
    body?: FysiekBezitUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/boedel/bezittingen';
};

export type PostApiV1BoedelBezittingenResponses = {
    /**
     * OK
     */
    200: FysiekBezitResponse;
};

export type PostApiV1BoedelBezittingenResponse = PostApiV1BoedelBezittingenResponses[keyof PostApiV1BoedelBezittingenResponses];

export type DeleteApiV1BoedelBezittingenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/boedel/bezittingen/{id}';
};

export type DeleteApiV1BoedelBezittingenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1BoedelBezittingenByIdData = {
    body?: FysiekBezitUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/boedel/bezittingen/{id}';
};

export type PutApiV1BoedelBezittingenByIdResponses = {
    /**
     * OK
     */
    200: FysiekBezitResponse;
};

export type PutApiV1BoedelBezittingenByIdResponse = PutApiV1BoedelBezittingenByIdResponses[keyof PutApiV1BoedelBezittingenByIdResponses];

export type GetApiV1BoedelBankrekeningenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/boedel/bankrekeningen';
};

export type GetApiV1BoedelBankrekeningenResponses = {
    /**
     * OK
     */
    200: Array<BankrekeningResponse>;
};

export type GetApiV1BoedelBankrekeningenResponse = GetApiV1BoedelBankrekeningenResponses[keyof GetApiV1BoedelBankrekeningenResponses];

export type PostApiV1BoedelBankrekeningenData = {
    body?: BankrekeningUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/boedel/bankrekeningen';
};

export type PostApiV1BoedelBankrekeningenResponses = {
    /**
     * OK
     */
    200: BankrekeningResponse;
};

export type PostApiV1BoedelBankrekeningenResponse = PostApiV1BoedelBankrekeningenResponses[keyof PostApiV1BoedelBankrekeningenResponses];

export type DeleteApiV1BoedelBankrekeningenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/boedel/bankrekeningen/{id}';
};

export type DeleteApiV1BoedelBankrekeningenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1BoedelBankrekeningenByIdData = {
    body?: BankrekeningUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/boedel/bankrekeningen/{id}';
};

export type PutApiV1BoedelBankrekeningenByIdResponses = {
    /**
     * OK
     */
    200: BankrekeningResponse;
};

export type PutApiV1BoedelBankrekeningenByIdResponse = PutApiV1BoedelBankrekeningenByIdResponses[keyof PutApiV1BoedelBankrekeningenByIdResponses];

export type GetApiV1BoedelVerzekeringenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/boedel/verzekeringen';
};

export type GetApiV1BoedelVerzekeringenResponses = {
    /**
     * OK
     */
    200: Array<VerzekeringResponse>;
};

export type GetApiV1BoedelVerzekeringenResponse = GetApiV1BoedelVerzekeringenResponses[keyof GetApiV1BoedelVerzekeringenResponses];

export type PostApiV1BoedelVerzekeringenData = {
    body?: VerzekeringUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/boedel/verzekeringen';
};

export type PostApiV1BoedelVerzekeringenResponses = {
    /**
     * OK
     */
    200: VerzekeringResponse;
};

export type PostApiV1BoedelVerzekeringenResponse = PostApiV1BoedelVerzekeringenResponses[keyof PostApiV1BoedelVerzekeringenResponses];

export type DeleteApiV1BoedelVerzekeringenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/boedel/verzekeringen/{id}';
};

export type DeleteApiV1BoedelVerzekeringenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1BoedelVerzekeringenByIdData = {
    body?: VerzekeringUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/boedel/verzekeringen/{id}';
};

export type PutApiV1BoedelVerzekeringenByIdResponses = {
    /**
     * OK
     */
    200: VerzekeringResponse;
};

export type PutApiV1BoedelVerzekeringenByIdResponse = PutApiV1BoedelVerzekeringenByIdResponses[keyof PutApiV1BoedelVerzekeringenByIdResponses];

export type GetApiV1BoedelSchuldenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/boedel/schulden';
};

export type GetApiV1BoedelSchuldenResponses = {
    /**
     * OK
     */
    200: Array<SchuldResponse>;
};

export type GetApiV1BoedelSchuldenResponse = GetApiV1BoedelSchuldenResponses[keyof GetApiV1BoedelSchuldenResponses];

export type PostApiV1BoedelSchuldenData = {
    body?: SchuldUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/boedel/schulden';
};

export type PostApiV1BoedelSchuldenResponses = {
    /**
     * OK
     */
    200: SchuldResponse;
};

export type PostApiV1BoedelSchuldenResponse = PostApiV1BoedelSchuldenResponses[keyof PostApiV1BoedelSchuldenResponses];

export type GetApiV1BoedelBezittingenByBezitIdSchuldenData = {
    body?: never;
    path: {
        bezitId: string;
    };
    query?: never;
    url: '/api/v1/boedel/bezittingen/{bezitId}/schulden';
};

export type GetApiV1BoedelBezittingenByBezitIdSchuldenResponses = {
    /**
     * OK
     */
    200: Array<SchuldResponse>;
};

export type GetApiV1BoedelBezittingenByBezitIdSchuldenResponse = GetApiV1BoedelBezittingenByBezitIdSchuldenResponses[keyof GetApiV1BoedelBezittingenByBezitIdSchuldenResponses];

export type PostApiV1BoedelBezittingenByBezitIdSchuldenData = {
    body?: BezitSchuldUpsertRequest;
    path: {
        bezitId: string;
    };
    query?: never;
    url: '/api/v1/boedel/bezittingen/{bezitId}/schulden';
};

export type PostApiV1BoedelBezittingenByBezitIdSchuldenResponses = {
    /**
     * OK
     */
    200: SchuldResponse;
};

export type PostApiV1BoedelBezittingenByBezitIdSchuldenResponse = PostApiV1BoedelBezittingenByBezitIdSchuldenResponses[keyof PostApiV1BoedelBezittingenByBezitIdSchuldenResponses];

export type DeleteApiV1BoedelBezittingenByBezitIdSchuldenBySchuldIdData = {
    body?: never;
    path: {
        bezitId: string;
        schuldId: string;
    };
    query?: never;
    url: '/api/v1/boedel/bezittingen/{bezitId}/schulden/{schuldId}';
};

export type DeleteApiV1BoedelBezittingenByBezitIdSchuldenBySchuldIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1BoedelBezittingenByBezitIdSchuldenBatchData = {
    body?: Array<BezitSchuldUpsertRequest>;
    path: {
        bezitId: string;
    };
    query?: never;
    url: '/api/v1/boedel/bezittingen/{bezitId}/schulden/batch';
};

export type PostApiV1BoedelBezittingenByBezitIdSchuldenBatchResponses = {
    /**
     * OK
     */
    200: Array<SchuldResponse>;
};

export type PostApiV1BoedelBezittingenByBezitIdSchuldenBatchResponse = PostApiV1BoedelBezittingenByBezitIdSchuldenBatchResponses[keyof PostApiV1BoedelBezittingenByBezitIdSchuldenBatchResponses];

export type DeleteApiV1BoedelSchuldenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/boedel/schulden/{id}';
};

export type DeleteApiV1BoedelSchuldenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1BoedelSchuldenByIdData = {
    body?: SchuldUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/boedel/schulden/{id}';
};

export type PutApiV1BoedelSchuldenByIdResponses = {
    /**
     * OK
     */
    200: SchuldResponse;
};

export type PutApiV1BoedelSchuldenByIdResponse = PutApiV1BoedelSchuldenByIdResponses[keyof PutApiV1BoedelSchuldenByIdResponses];

export type GetApiV1DigitaalBezitAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/digitaal-bezit/accounts';
};

export type GetApiV1DigitaalBezitAccountsResponses = {
    /**
     * OK
     */
    200: Array<DigitaalAccountResponse>;
};

export type GetApiV1DigitaalBezitAccountsResponse = GetApiV1DigitaalBezitAccountsResponses[keyof GetApiV1DigitaalBezitAccountsResponses];

export type PostApiV1DigitaalBezitAccountsData = {
    body?: DigitaalAccountUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/digitaal-bezit/accounts';
};

export type PostApiV1DigitaalBezitAccountsResponses = {
    /**
     * OK
     */
    200: DigitaalAccountResponse;
};

export type PostApiV1DigitaalBezitAccountsResponse = PostApiV1DigitaalBezitAccountsResponses[keyof PostApiV1DigitaalBezitAccountsResponses];

export type DeleteApiV1DigitaalBezitAccountsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/digitaal-bezit/accounts/{id}';
};

export type DeleteApiV1DigitaalBezitAccountsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1DigitaalBezitAccountsByIdData = {
    body?: DigitaalAccountUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/digitaal-bezit/accounts/{id}';
};

export type PutApiV1DigitaalBezitAccountsByIdResponses = {
    /**
     * OK
     */
    200: DigitaalAccountResponse;
};

export type PutApiV1DigitaalBezitAccountsByIdResponse = PutApiV1DigitaalBezitAccountsByIdResponses[keyof PutApiV1DigitaalBezitAccountsByIdResponses];

export type GetApiV1DigitaalBezitWachtwoordenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/digitaal-bezit/wachtwoorden';
};

export type GetApiV1DigitaalBezitWachtwoordenResponses = {
    /**
     * OK
     */
    200: Array<WachtwoordEntryResponse>;
};

export type GetApiV1DigitaalBezitWachtwoordenResponse = GetApiV1DigitaalBezitWachtwoordenResponses[keyof GetApiV1DigitaalBezitWachtwoordenResponses];

export type PostApiV1DigitaalBezitWachtwoordenData = {
    body?: WachtwoordEntryCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/digitaal-bezit/wachtwoorden';
};

export type PostApiV1DigitaalBezitWachtwoordenResponses = {
    /**
     * OK
     */
    200: WachtwoordEntryResponse;
};

export type PostApiV1DigitaalBezitWachtwoordenResponse = PostApiV1DigitaalBezitWachtwoordenResponses[keyof PostApiV1DigitaalBezitWachtwoordenResponses];

export type GetApiV1DigitaalBezitWachtwoordenByIdOntsluitelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/digitaal-bezit/wachtwoorden/{id}/ontsluitel';
};

export type GetApiV1DigitaalBezitWachtwoordenByIdOntsluitelResponses = {
    /**
     * OK
     */
    200: WachtwoordOntsluitelResponse;
};

export type GetApiV1DigitaalBezitWachtwoordenByIdOntsluitelResponse = GetApiV1DigitaalBezitWachtwoordenByIdOntsluitelResponses[keyof GetApiV1DigitaalBezitWachtwoordenByIdOntsluitelResponses];

export type DeleteApiV1DigitaalBezitWachtwoordenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/digitaal-bezit/wachtwoorden/{id}';
};

export type DeleteApiV1DigitaalBezitWachtwoordenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1DigitaalBezitWachtwoordenByIdData = {
    body?: WachtwoordEntryUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/digitaal-bezit/wachtwoorden/{id}';
};

export type PutApiV1DigitaalBezitWachtwoordenByIdResponses = {
    /**
     * OK
     */
    200: WachtwoordEntryResponse;
};

export type PutApiV1DigitaalBezitWachtwoordenByIdResponse = PutApiV1DigitaalBezitWachtwoordenByIdResponses[keyof PutApiV1DigitaalBezitWachtwoordenByIdResponses];

export type PostApiV1DigitaalBezitWachtwoordenImporterenData = {
    body?: {
        Bestand: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/digitaal-bezit/wachtwoorden/importeren';
};

export type PostApiV1DigitaalBezitWachtwoordenImporterenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1DigitaalBezitCryptoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/digitaal-bezit/crypto';
};

export type GetApiV1DigitaalBezitCryptoResponses = {
    /**
     * OK
     */
    200: Array<CryptoWalletResponse>;
};

export type GetApiV1DigitaalBezitCryptoResponse = GetApiV1DigitaalBezitCryptoResponses[keyof GetApiV1DigitaalBezitCryptoResponses];

export type PostApiV1DigitaalBezitCryptoData = {
    body?: CryptoWalletUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/digitaal-bezit/crypto';
};

export type PostApiV1DigitaalBezitCryptoResponses = {
    /**
     * OK
     */
    200: CryptoWalletResponse;
};

export type PostApiV1DigitaalBezitCryptoResponse = PostApiV1DigitaalBezitCryptoResponses[keyof PostApiV1DigitaalBezitCryptoResponses];

export type DeleteApiV1DigitaalBezitCryptoByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/digitaal-bezit/crypto/{id}';
};

export type DeleteApiV1DigitaalBezitCryptoByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1DigitaalBezitCryptoByIdData = {
    body?: CryptoWalletUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/digitaal-bezit/crypto/{id}';
};

export type PutApiV1DigitaalBezitCryptoByIdResponses = {
    /**
     * OK
     */
    200: CryptoWalletResponse;
};

export type PutApiV1DigitaalBezitCryptoByIdResponse = PutApiV1DigitaalBezitCryptoByIdResponses[keyof PutApiV1DigitaalBezitCryptoByIdResponses];

export type GetApiV1DigitaalBezitCryptoByIdOntsluitelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/digitaal-bezit/crypto/{id}/ontsluitel';
};

export type GetApiV1DigitaalBezitCryptoByIdOntsluitelResponses = {
    /**
     * OK
     */
    200: CryptoWalletOntsluitelResponse;
};

export type GetApiV1DigitaalBezitCryptoByIdOntsluitelResponse = GetApiV1DigitaalBezitCryptoByIdOntsluitelResponses[keyof GetApiV1DigitaalBezitCryptoByIdOntsluitelResponses];

export type GetApiV1DocumentenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/documenten';
};

export type GetApiV1DocumentenResponses = {
    /**
     * OK
     */
    200: Array<DocumentResponse>;
};

export type GetApiV1DocumentenResponse = GetApiV1DocumentenResponses[keyof GetApiV1DocumentenResponses];

export type DeleteApiV1DocumentenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/documenten/{id}';
};

export type DeleteApiV1DocumentenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1DocumentenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/documenten/{id}';
};

export type GetApiV1DocumentenByIdResponses = {
    /**
     * OK
     */
    200: DocumentResponse;
};

export type GetApiV1DocumentenByIdResponse = GetApiV1DocumentenByIdResponses[keyof GetApiV1DocumentenByIdResponses];

export type PatchApiV1DocumentenByIdData = {
    body?: DocumentUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/documenten/{id}';
};

export type PatchApiV1DocumentenByIdResponses = {
    /**
     * OK
     */
    200: DocumentResponse;
};

export type PatchApiV1DocumentenByIdResponse = PatchApiV1DocumentenByIdResponses[keyof PatchApiV1DocumentenByIdResponses];

export type GetApiV1DocumentenByIdVersiesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/documenten/{id}/versies';
};

export type GetApiV1DocumentenByIdVersiesResponses = {
    /**
     * OK
     */
    200: Array<DocumentVersieResponse>;
};

export type GetApiV1DocumentenByIdVersiesResponse = GetApiV1DocumentenByIdVersiesResponses[keyof GetApiV1DocumentenByIdVersiesResponses];

export type DeleteApiV1DocumentenByIdAlleVersiesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/documenten/{id}/alle-versies';
};

export type DeleteApiV1DocumentenByIdAlleVersiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1DocumentenUploadenData = {
    body?: {
        Naam?: string;
        Categorie?: string;
        Bestand?: Blob | File;
        Notities?: string;
        VerlooptOp?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/documenten/uploaden';
};

export type PostApiV1DocumentenUploadenResponses = {
    /**
     * OK
     */
    200: DocumentResponse;
};

export type PostApiV1DocumentenUploadenResponse = PostApiV1DocumentenUploadenResponses[keyof PostApiV1DocumentenUploadenResponses];

export type GetApiV1DocumentenByIdDownloadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/documenten/{id}/download';
};

export type GetApiV1DocumentenByIdDownloadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1DonorData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/donor';
};

export type GetApiV1DonorResponses = {
    /**
     * OK
     */
    200: DonorRegistratieResponse;
};

export type GetApiV1DonorResponse = GetApiV1DonorResponses[keyof GetApiV1DonorResponses];

export type PutApiV1DonorData = {
    body?: DonorRegistratieUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/donor';
};

export type PutApiV1DonorResponses = {
    /**
     * OK
     */
    200: DonorRegistratieResponse;
};

export type PutApiV1DonorResponse = PutApiV1DonorResponses[keyof PutApiV1DonorResponses];

export type GetApiV1DonorOrgaankeuzesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/donor/orgaankeuzes';
};

export type GetApiV1DonorOrgaankeuzesResponses = {
    /**
     * OK
     */
    200: Array<OrgaanKeuzeResponse>;
};

export type GetApiV1DonorOrgaankeuzesResponse = GetApiV1DonorOrgaankeuzesResponses[keyof GetApiV1DonorOrgaankeuzesResponses];

export type PostApiV1DonorOrgaankeuzesData = {
    body?: OrgaanKeuzeUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/donor/orgaankeuzes';
};

export type PostApiV1DonorOrgaankeuzesResponses = {
    /**
     * OK
     */
    200: OrgaanKeuzeResponse;
};

export type PostApiV1DonorOrgaankeuzesResponse = PostApiV1DonorOrgaankeuzesResponses[keyof PostApiV1DonorOrgaankeuzesResponses];

export type DeleteApiV1DonorOrgaankeuzesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/donor/orgaankeuzes/{id}';
};

export type DeleteApiV1DonorOrgaankeuzesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1DonorOrgaankeuzesByIdData = {
    body?: OrgaanKeuzeUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/donor/orgaankeuzes/{id}';
};

export type PutApiV1DonorOrgaankeuzesByIdResponses = {
    /**
     * OK
     */
    200: OrgaanKeuzeResponse;
};

export type PutApiV1DonorOrgaankeuzesByIdResponse = PutApiV1DonorOrgaankeuzesByIdResponses[keyof PutApiV1DonorOrgaankeuzesByIdResponses];

export type PutApiV1DonorOrgaankeuzesBatchData = {
    body?: Array<OrgaanKeuzeUpsertRequest>;
    path?: never;
    query?: never;
    url: '/api/v1/donor/orgaankeuzes/batch';
};

export type PutApiV1DonorOrgaankeuzesBatchResponses = {
    /**
     * OK
     */
    200: Array<OrgaanKeuzeResponse>;
};

export type PutApiV1DonorOrgaankeuzesBatchResponse = PutApiV1DonorOrgaankeuzesBatchResponses[keyof PutApiV1DonorOrgaankeuzesBatchResponses];

export type GetApiV1EigenaarData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eigenaar';
};

export type GetApiV1EigenaarResponses = {
    /**
     * OK
     */
    200: EigenaarResponse;
};

export type GetApiV1EigenaarResponse = GetApiV1EigenaarResponses[keyof GetApiV1EigenaarResponses];

export type PostApiV1EigenaarData = {
    body?: EigenaarUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/eigenaar';
};

export type PostApiV1EigenaarResponses = {
    /**
     * OK
     */
    200: EigenaarResponse;
};

export type PostApiV1EigenaarResponse = PostApiV1EigenaarResponses[keyof PostApiV1EigenaarResponses];

export type PutApiV1EigenaarData = {
    body?: EigenaarUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/eigenaar';
};

export type PutApiV1EigenaarResponses = {
    /**
     * OK
     */
    200: EigenaarResponse;
};

export type PutApiV1EigenaarResponse = PutApiV1EigenaarResponses[keyof PutApiV1EigenaarResponses];

export type DeleteApiV1EigenaarFotoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eigenaar/foto';
};

export type DeleteApiV1EigenaarFotoResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1EigenaarFotoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eigenaar/foto';
};

export type GetApiV1EigenaarFotoResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1EigenaarFotoData = {
    body?: {
        Bestand: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/eigenaar/foto';
};

export type PostApiV1EigenaarFotoResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1EigenaarOnboardingVoltooidData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eigenaar/onboarding-voltooid';
};

export type PostApiV1EigenaarOnboardingVoltooidResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1EigenaarOnboardingStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eigenaar/onboarding-status';
};

export type GetApiV1EigenaarOnboardingStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ErfgenamenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/erfgenamen';
};

export type GetApiV1ErfgenamenResponses = {
    /**
     * OK
     */
    200: Array<ErfgenaamResponse>;
};

export type GetApiV1ErfgenamenResponse = GetApiV1ErfgenamenResponses[keyof GetApiV1ErfgenamenResponses];

export type PostApiV1ErfgenamenData = {
    body?: ErfgenaamUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/erfgenamen';
};

export type PostApiV1ErfgenamenResponses = {
    /**
     * OK
     */
    200: ErfgenaamResponse;
};

export type PostApiV1ErfgenamenResponse = PostApiV1ErfgenamenResponses[keyof PostApiV1ErfgenamenResponses];

export type DeleteApiV1ErfgenamenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/erfgenamen/{id}';
};

export type DeleteApiV1ErfgenamenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ErfgenamenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/erfgenamen/{id}';
};

export type GetApiV1ErfgenamenByIdResponses = {
    /**
     * OK
     */
    200: ErfgenaamResponse;
};

export type GetApiV1ErfgenamenByIdResponse = GetApiV1ErfgenamenByIdResponses[keyof GetApiV1ErfgenamenByIdResponses];

export type PutApiV1ErfgenamenByIdData = {
    body?: ErfgenaamUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/erfgenamen/{id}';
};

export type PutApiV1ErfgenamenByIdResponses = {
    /**
     * OK
     */
    200: ErfgenaamResponse;
};

export type PutApiV1ErfgenamenByIdResponse = PutApiV1ErfgenamenByIdResponses[keyof PutApiV1ErfgenamenByIdResponses];

export type GetApiV1ErfgenamenErfbelastingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/erfgenamen/erfbelasting';
};

export type GetApiV1ErfgenamenErfbelastingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1EuthanasieData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/euthanasie';
};

export type GetApiV1EuthanasieResponses = {
    /**
     * OK
     */
    200: WilsverklaringResponse;
};

export type GetApiV1EuthanasieResponse = GetApiV1EuthanasieResponses[keyof GetApiV1EuthanasieResponses];

export type PutApiV1EuthanasieData = {
    body?: WilsverklaringUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/euthanasie';
};

export type PutApiV1EuthanasieResponses = {
    /**
     * OK
     */
    200: WilsverklaringResponse;
};

export type PutApiV1EuthanasieResponse = PutApiV1EuthanasieResponses[keyof PutApiV1EuthanasieResponses];

export type GetApiV1EuthanasieVoorwaardenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/euthanasie/voorwaarden';
};

export type GetApiV1EuthanasieVoorwaardenResponses = {
    /**
     * OK
     */
    200: Array<VoorwaardeResponse>;
};

export type GetApiV1EuthanasieVoorwaardenResponse = GetApiV1EuthanasieVoorwaardenResponses[keyof GetApiV1EuthanasieVoorwaardenResponses];

export type PostApiV1EuthanasieVoorwaardenData = {
    body?: VoorwaardeUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/euthanasie/voorwaarden';
};

export type PostApiV1EuthanasieVoorwaardenResponses = {
    /**
     * OK
     */
    200: VoorwaardeResponse;
};

export type PostApiV1EuthanasieVoorwaardenResponse = PostApiV1EuthanasieVoorwaardenResponses[keyof PostApiV1EuthanasieVoorwaardenResponses];

export type DeleteApiV1EuthanasieVoorwaardenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/euthanasie/voorwaarden/{id}';
};

export type DeleteApiV1EuthanasieVoorwaardenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1EuthanasieVoorwaardenByIdData = {
    body?: VoorwaardeUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/euthanasie/voorwaarden/{id}';
};

export type PutApiV1EuthanasieVoorwaardenByIdResponses = {
    /**
     * OK
     */
    200: VoorwaardeResponse;
};

export type PutApiV1EuthanasieVoorwaardenByIdResponse = PutApiV1EuthanasieVoorwaardenByIdResponses[keyof PutApiV1EuthanasieVoorwaardenByIdResponses];

export type GetApiV1ExportStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/status';
};

export type GetApiV1ExportStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportTestamentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/testament';
};

export type GetApiV1ExportTestamentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportEuthanasieData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/euthanasie';
};

export type GetApiV1ExportEuthanasieResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportDonorData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/donor';
};

export type GetApiV1ExportDonorResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportDigitaalBezitData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/digitaal-bezit';
};

export type GetApiV1ExportDigitaalBezitResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportBoedelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/boedel';
};

export type GetApiV1ExportBoedelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportUitvaartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/uitvaart';
};

export type GetApiV1ExportUitvaartResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportDocumentenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/documenten';
};

export type GetApiV1ExportDocumentenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportCompleetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/compleet';
};

export type GetApiV1ExportCompleetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportNoodkaartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/noodkaart';
};

export type GetApiV1ExportNoodkaartResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportTestamentConceptData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/testament-concept';
};

export type GetApiV1ExportTestamentConceptResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportWilsverklaringData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/wilsverklaring';
};

export type GetApiV1ExportWilsverklaringResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportNoodprocedureData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/noodprocedure';
};

export type GetApiV1ExportNoodprocedureResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportBoedelbeschrijvingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/boedelbeschrijving';
};

export type GetApiV1ExportBoedelbeschrijvingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportExecuteurRapportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/executeur-rapport';
};

export type GetApiV1ExportExecuteurRapportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportNotarisData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/notaris';
};

export type GetApiV1ExportNotarisResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportNabestaandenInstructieData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/nabestaanden-instructie';
};

export type GetApiV1ExportNabestaandenInstructieResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportErfgenaamByErfgenaamIdData = {
    body?: never;
    path: {
        erfgenaamId: string;
    };
    query?: never;
    url: '/api/v1/export/erfgenaam/{erfgenaamId}';
};

export type GetApiV1ExportErfgenaamByErfgenaamIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportDelenByErfgenaamIdData = {
    body?: never;
    path: {
        erfgenaamId: string;
    };
    query?: never;
    url: '/api/v1/export/delen/{erfgenaamId}';
};

export type GetApiV1ExportDelenByErfgenaamIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1ExportAllesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/alles';
};

export type PostApiV1ExportAllesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1ExportBackupEncryptedData = {
    body?: EncryptedBackupRequest;
    path?: never;
    query?: never;
    url: '/api/v1/export/backup/encrypted';
};

export type PostApiV1ExportBackupEncryptedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportCsvErfgenamenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/csv/erfgenamen';
};

export type GetApiV1ExportCsvErfgenamenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportCsvBezittingenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/csv/bezittingen';
};

export type GetApiV1ExportCsvBezittingenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportCsvBankrekeningenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/csv/bankrekeningen';
};

export type GetApiV1ExportCsvBankrekeningenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportCsvVerzekeringenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/csv/verzekeringen';
};

export type GetApiV1ExportCsvVerzekeringenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportCsvSchuldenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/csv/schulden';
};

export type GetApiV1ExportCsvSchuldenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportCsvNoodcontactenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/csv/noodcontacten';
};

export type GetApiV1ExportCsvNoodcontactenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/json';
};

export type GetApiV1ExportJsonResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportXmlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/xml';
};

export type GetApiV1ExportXmlResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ExportNuvData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export/nuv';
};

export type GetApiV1ExportNuvResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1NoodcontactenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/noodcontacten';
};

export type GetApiV1NoodcontactenResponses = {
    /**
     * OK
     */
    200: Array<NoodcontactResponse>;
};

export type GetApiV1NoodcontactenResponse = GetApiV1NoodcontactenResponses[keyof GetApiV1NoodcontactenResponses];

export type PostApiV1NoodcontactenData = {
    body?: NoodcontactUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/noodcontacten';
};

export type PostApiV1NoodcontactenResponses = {
    /**
     * OK
     */
    200: NoodcontactResponse;
};

export type PostApiV1NoodcontactenResponse = PostApiV1NoodcontactenResponses[keyof PostApiV1NoodcontactenResponses];

export type DeleteApiV1NoodcontactenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/noodcontacten/{id}';
};

export type DeleteApiV1NoodcontactenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1NoodcontactenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/noodcontacten/{id}';
};

export type GetApiV1NoodcontactenByIdResponses = {
    /**
     * OK
     */
    200: NoodcontactResponse;
};

export type GetApiV1NoodcontactenByIdResponse = GetApiV1NoodcontactenByIdResponses[keyof GetApiV1NoodcontactenByIdResponses];

export type PutApiV1NoodcontactenByIdData = {
    body?: NoodcontactUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/noodcontacten/{id}';
};

export type PutApiV1NoodcontactenByIdResponses = {
    /**
     * OK
     */
    200: NoodcontactResponse;
};

export type PutApiV1NoodcontactenByIdResponse = PutApiV1NoodcontactenByIdResponses[keyof PutApiV1NoodcontactenByIdResponses];

export type GetApiV1NoodcontactenGedeeldExportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/noodcontacten/gedeeld/export';
};

export type GetApiV1NoodcontactenGedeeldExportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1NoodcontactenGedeeldImportData = {
    body?: Array<GedeeldNoodcontactDto>;
    path?: never;
    query?: never;
    url: '/api/v1/noodcontacten/gedeeld/import';
};

export type PostApiV1NoodcontactenGedeeldImportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1NotitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notities';
};

export type GetApiV1NotitiesResponses = {
    /**
     * OK
     */
    200: Array<SectieNotitieResponse>;
};

export type GetApiV1NotitiesResponse = GetApiV1NotitiesResponses[keyof GetApiV1NotitiesResponses];

export type DeleteApiV1NotitiesBySectieData = {
    body?: never;
    path: {
        sectie: string;
    };
    query?: never;
    url: '/api/v1/notities/{sectie}';
};

export type DeleteApiV1NotitiesBySectieResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1NotitiesBySectieData = {
    body?: never;
    path: {
        sectie: string;
    };
    query?: never;
    url: '/api/v1/notities/{sectie}';
};

export type GetApiV1NotitiesBySectieResponses = {
    /**
     * OK
     */
    200: SectieNotitieResponse;
};

export type GetApiV1NotitiesBySectieResponse = GetApiV1NotitiesBySectieResponses[keyof GetApiV1NotitiesBySectieResponses];

export type PutApiV1NotitiesBySectieData = {
    body?: SectieNotitieUpsertRequest;
    path: {
        sectie: string;
    };
    query?: never;
    url: '/api/v1/notities/{sectie}';
};

export type PutApiV1NotitiesBySectieResponses = {
    /**
     * OK
     */
    200: SectieNotitieResponse;
};

export type PutApiV1NotitiesBySectieResponse = PutApiV1NotitiesBySectieResponses[keyof PutApiV1NotitiesBySectieResponses];

export type GetApiV1ProfielenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profielen';
};

export type GetApiV1ProfielenResponses = {
    /**
     * OK
     */
    200: Array<ProfileResponse>;
};

export type GetApiV1ProfielenResponse = GetApiV1ProfielenResponses[keyof GetApiV1ProfielenResponses];

export type PostApiV1ProfielenData = {
    body?: CreateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/v1/profielen';
};

export type PostApiV1ProfielenResponses = {
    /**
     * OK
     */
    200: ProfileResponse;
};

export type PostApiV1ProfielenResponse = PostApiV1ProfielenResponses[keyof PostApiV1ProfielenResponses];

export type DeleteApiV1ProfielenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/profielen/{id}';
};

export type DeleteApiV1ProfielenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1ShamirGenereerData = {
    body?: GenereerSharesRequest;
    path?: never;
    query?: never;
    url: '/api/v1/shamir/genereer';
};

export type PostApiV1ShamirGenereerResponses = {
    /**
     * OK
     */
    200: GenereerSharesResponse;
};

export type PostApiV1ShamirGenereerResponse = PostApiV1ShamirGenereerResponses[keyof PostApiV1ShamirGenereerResponses];

export type PostApiV1ShamirReconstrueerEnOntgrendelData = {
    body?: ReconstrueerRequest;
    path?: never;
    query?: never;
    url: '/api/v1/shamir/reconstrueer-en-ontgrendel';
};

export type PostApiV1ShamirReconstrueerEnOntgrendelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ShamirDrempelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/shamir/drempel';
};

export type GetApiV1ShamirDrempelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status';
};

export type GetApiV1StatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1StatusCompleetheidData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/compleetheid';
};

export type GetApiV1StatusCompleetheidResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1StatusCompleetheidGranulairData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/compleetheid/granulair';
};

export type GetApiV1StatusCompleetheidGranulairResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1StatusMeldingenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/meldingen';
};

export type GetApiV1StatusMeldingenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1StatusSuggestiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/suggesties';
};

export type GetApiV1StatusSuggestiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1StatusStatistiekenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/statistieken';
};

export type GetApiV1StatusStatistiekenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1StatusActualisatieData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/actualisatie';
};

export type GetApiV1StatusActualisatieResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1StatusActualisatieByDomeinData = {
    body?: never;
    path: {
        domein: string;
    };
    query?: never;
    url: '/api/v1/status/actualisatie/{domein}';
};

export type DeleteApiV1StatusActualisatieByDomeinResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1StatusActualisatieByDomeinData = {
    body?: never;
    path: {
        domein: string;
    };
    query?: never;
    url: '/api/v1/status/actualisatie/{domein}';
};

export type PostApiV1StatusActualisatieByDomeinResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1StatusActualisatieAllesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/actualisatie/alles';
};

export type PostApiV1StatusActualisatieAllesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1StatusTijdlijnBekekenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/tijdlijn-bekeken';
};

export type PostApiV1StatusTijdlijnBekekenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1StatusBackupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/backup';
};

export type GetApiV1StatusBackupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1StatusBackupBevestigdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/backup/bevestigd';
};

export type PostApiV1StatusBackupBevestigdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1StatusSnapshotData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/snapshot';
};

export type GetApiV1StatusSnapshotResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1TestamentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/testament';
};

export type GetApiV1TestamentResponses = {
    /**
     * OK
     */
    200: TestamentInfoResponse;
};

export type GetApiV1TestamentResponse = GetApiV1TestamentResponses[keyof GetApiV1TestamentResponses];

export type PutApiV1TestamentData = {
    body?: TestamentInfoUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/testament';
};

export type PutApiV1TestamentResponses = {
    /**
     * OK
     */
    200: TestamentInfoResponse;
};

export type PutApiV1TestamentResponse = PutApiV1TestamentResponses[keyof PutApiV1TestamentResponses];

export type GetApiV1TestamentLegitimairePortieCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/testament/legitimaire-portie-check';
};

export type GetApiV1TestamentLegitimairePortieCheckResponses = {
    /**
     * OK
     */
    200: LegitimairePortieCheckResult;
};

export type GetApiV1TestamentLegitimairePortieCheckResponse = GetApiV1TestamentLegitimairePortieCheckResponses[keyof GetApiV1TestamentLegitimairePortieCheckResponses];

export type GetApiV1TestamentBegunstigdenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/testament/begunstigden';
};

export type GetApiV1TestamentBegunstigdenResponses = {
    /**
     * OK
     */
    200: Array<BegunstigdeResponse>;
};

export type GetApiV1TestamentBegunstigdenResponse = GetApiV1TestamentBegunstigdenResponses[keyof GetApiV1TestamentBegunstigdenResponses];

export type PostApiV1TestamentBegunstigdenData = {
    body?: BegunstigdeUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/testament/begunstigden';
};

export type PostApiV1TestamentBegunstigdenResponses = {
    /**
     * OK
     */
    200: BegunstigdeResponse;
};

export type PostApiV1TestamentBegunstigdenResponse = PostApiV1TestamentBegunstigdenResponses[keyof PostApiV1TestamentBegunstigdenResponses];

export type DeleteApiV1TestamentBegunstigdenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/testament/begunstigden/{id}';
};

export type DeleteApiV1TestamentBegunstigdenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1TestamentBegunstigdenByIdData = {
    body?: BegunstigdeUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/testament/begunstigden/{id}';
};

export type PutApiV1TestamentBegunstigdenByIdResponses = {
    /**
     * OK
     */
    200: BegunstigdeResponse;
};

export type PutApiV1TestamentBegunstigdenByIdResponse = PutApiV1TestamentBegunstigdenByIdResponses[keyof PutApiV1TestamentBegunstigdenByIdResponses];

export type GetApiV1TestamentExecuteursData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/testament/executeurs';
};

export type GetApiV1TestamentExecuteursResponses = {
    /**
     * OK
     */
    200: Array<ExecuteurResponse>;
};

export type GetApiV1TestamentExecuteursResponse = GetApiV1TestamentExecuteursResponses[keyof GetApiV1TestamentExecuteursResponses];

export type PostApiV1TestamentExecuteursData = {
    body?: ExecuteurUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/testament/executeurs';
};

export type PostApiV1TestamentExecuteursResponses = {
    /**
     * OK
     */
    200: ExecuteurResponse;
};

export type PostApiV1TestamentExecuteursResponse = PostApiV1TestamentExecuteursResponses[keyof PostApiV1TestamentExecuteursResponses];

export type DeleteApiV1TestamentExecuteursByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/testament/executeurs/{id}';
};

export type DeleteApiV1TestamentExecuteursByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1TestamentExecuteursByIdData = {
    body?: ExecuteurUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/testament/executeurs/{id}';
};

export type PutApiV1TestamentExecuteursByIdResponses = {
    /**
     * OK
     */
    200: ExecuteurResponse;
};

export type PutApiV1TestamentExecuteursByIdResponse = PutApiV1TestamentExecuteursByIdResponses[keyof PutApiV1TestamentExecuteursByIdResponses];

export type GetApiV1TestamentJuridischeCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/testament/juridische-check';
};

export type GetApiV1TestamentJuridischeCheckResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1TestamentSnapshotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/testament/snapshots';
};

export type GetApiV1TestamentSnapshotsResponses = {
    /**
     * OK
     */
    200: Array<TestamentSnapshotResponse>;
};

export type GetApiV1TestamentSnapshotsResponse = GetApiV1TestamentSnapshotsResponses[keyof GetApiV1TestamentSnapshotsResponses];

export type PostApiV1TestamentSnapshotsData = {
    body?: TestamentSnapshotCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/testament/snapshots';
};

export type PostApiV1TestamentSnapshotsResponses = {
    /**
     * OK
     */
    200: TestamentSnapshotResponse;
};

export type PostApiV1TestamentSnapshotsResponse = PostApiV1TestamentSnapshotsResponses[keyof PostApiV1TestamentSnapshotsResponses];

export type DeleteApiV1TestamentSnapshotsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/testament/snapshots/{id}';
};

export type DeleteApiV1TestamentSnapshotsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1TestamentSnapshotsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/testament/snapshots/{id}';
};

export type GetApiV1TestamentSnapshotsByIdResponses = {
    /**
     * OK
     */
    200: TestamentSnapshotDetailResponse;
};

export type GetApiV1TestamentSnapshotsByIdResponse = GetApiV1TestamentSnapshotsByIdResponses[keyof GetApiV1TestamentSnapshotsByIdResponses];

export type GetApiV1TestamentSnapshotsVergelijkData = {
    body?: never;
    path?: never;
    query?: {
        versie1Id?: string;
        versie2Id?: string;
    };
    url: '/api/v1/testament/snapshots/vergelijk';
};

export type GetApiV1TestamentSnapshotsVergelijkResponses = {
    /**
     * OK
     */
    200: TestamentVergelijkingResponse;
};

export type GetApiV1TestamentSnapshotsVergelijkResponse = GetApiV1TestamentSnapshotsVergelijkResponses[keyof GetApiV1TestamentSnapshotsVergelijkResponses];

export type GetApiV1ToewijzingenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/toewijzingen';
};

export type GetApiV1ToewijzingenResponses = {
    /**
     * OK
     */
    200: Array<ErfgenaamToewijzingResponse>;
};

export type GetApiV1ToewijzingenResponse = GetApiV1ToewijzingenResponses[keyof GetApiV1ToewijzingenResponses];

export type PostApiV1ToewijzingenData = {
    body?: ErfgenaamToewijzingUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/toewijzingen';
};

export type PostApiV1ToewijzingenResponses = {
    /**
     * OK
     */
    200: ErfgenaamToewijzingResponse;
};

export type PostApiV1ToewijzingenResponse = PostApiV1ToewijzingenResponses[keyof PostApiV1ToewijzingenResponses];

export type GetApiV1ToewijzingenErfgenaamByErfgenaamIdData = {
    body?: never;
    path: {
        erfgenaamId: string;
    };
    query?: never;
    url: '/api/v1/toewijzingen/erfgenaam/{erfgenaamId}';
};

export type GetApiV1ToewijzingenErfgenaamByErfgenaamIdResponses = {
    /**
     * OK
     */
    200: Array<ErfgenaamToewijzingResponse>;
};

export type GetApiV1ToewijzingenErfgenaamByErfgenaamIdResponse = GetApiV1ToewijzingenErfgenaamByErfgenaamIdResponses[keyof GetApiV1ToewijzingenErfgenaamByErfgenaamIdResponses];

export type DeleteApiV1ToewijzingenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/toewijzingen/{id}';
};

export type DeleteApiV1ToewijzingenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1ToewijzingenByIdData = {
    body?: ErfgenaamToewijzingUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/toewijzingen/{id}';
};

export type PutApiV1ToewijzingenByIdResponses = {
    /**
     * OK
     */
    200: ErfgenaamToewijzingResponse;
};

export type PutApiV1ToewijzingenByIdResponse = PutApiV1ToewijzingenByIdResponses[keyof PutApiV1ToewijzingenByIdResponses];

export type GetApiV1UitvaartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/uitvaart';
};

export type GetApiV1UitvaartResponses = {
    /**
     * OK
     */
    200: UitvaartWensenResponse;
};

export type GetApiV1UitvaartResponse = GetApiV1UitvaartResponses[keyof GetApiV1UitvaartResponses];

export type PutApiV1UitvaartData = {
    body?: UitvaartWensenUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/uitvaart';
};

export type PutApiV1UitvaartResponses = {
    /**
     * OK
     */
    200: UitvaartWensenResponse;
};

export type PutApiV1UitvaartResponse = PutApiV1UitvaartResponses[keyof PutApiV1UitvaartResponses];

export type GetApiV1UitvaartDetailsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/uitvaart/details';
};

export type GetApiV1UitvaartDetailsResponses = {
    /**
     * OK
     */
    200: Array<CeremonieDetailResponse>;
};

export type GetApiV1UitvaartDetailsResponse = GetApiV1UitvaartDetailsResponses[keyof GetApiV1UitvaartDetailsResponses];

export type PostApiV1UitvaartDetailsData = {
    body?: CeremonieDetailUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/uitvaart/details';
};

export type PostApiV1UitvaartDetailsResponses = {
    /**
     * OK
     */
    200: CeremonieDetailResponse;
};

export type PostApiV1UitvaartDetailsResponse = PostApiV1UitvaartDetailsResponses[keyof PostApiV1UitvaartDetailsResponses];

export type DeleteApiV1UitvaartDetailsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/uitvaart/details/{id}';
};

export type DeleteApiV1UitvaartDetailsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1UitvaartDetailsByIdData = {
    body?: CeremonieDetailUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/uitvaart/details/{id}';
};

export type PutApiV1UitvaartDetailsByIdResponses = {
    /**
     * OK
     */
    200: CeremonieDetailResponse;
};

export type PutApiV1UitvaartDetailsByIdResponse = PutApiV1UitvaartDetailsByIdResponses[keyof PutApiV1UitvaartDetailsByIdResponses];

export type GetApiV1UitvaartGenodigdenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/uitvaart/genodigden';
};

export type GetApiV1UitvaartGenodigdenResponses = {
    /**
     * OK
     */
    200: Array<UitvaartGenodigdeResponse>;
};

export type GetApiV1UitvaartGenodigdenResponse = GetApiV1UitvaartGenodigdenResponses[keyof GetApiV1UitvaartGenodigdenResponses];

export type PostApiV1UitvaartGenodigdenData = {
    body?: UitvaartGenodigdeUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/uitvaart/genodigden';
};

export type PostApiV1UitvaartGenodigdenResponses = {
    /**
     * OK
     */
    200: UitvaartGenodigdeResponse;
};

export type PostApiV1UitvaartGenodigdenResponse = PostApiV1UitvaartGenodigdenResponses[keyof PostApiV1UitvaartGenodigdenResponses];

export type DeleteApiV1UitvaartGenodigdenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/uitvaart/genodigden/{id}';
};

export type DeleteApiV1UitvaartGenodigdenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1UitvaartGenodigdenByIdData = {
    body?: UitvaartGenodigdeUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/uitvaart/genodigden/{id}';
};

export type PutApiV1UitvaartGenodigdenByIdResponses = {
    /**
     * OK
     */
    200: UitvaartGenodigdeResponse;
};

export type PutApiV1UitvaartGenodigdenByIdResponse = PutApiV1UitvaartGenodigdenByIdResponses[keyof PutApiV1UitvaartGenodigdenByIdResponses];

export type GetApiV1VideoboodschappenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/videoboodschappen';
};

export type GetApiV1VideoboodschappenResponses = {
    /**
     * OK
     */
    200: Array<VideoboodschapResponse>;
};

export type GetApiV1VideoboodschappenResponse = GetApiV1VideoboodschappenResponses[keyof GetApiV1VideoboodschappenResponses];

export type GetApiV1VideoboodschappenLimietData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/videoboodschappen/limiet';
};

export type GetApiV1VideoboodschappenLimietResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1VideoboodschappenUploadenData = {
    body?: {
        Bestand: Blob | File;
        Titel: string;
        Beschrijving?: string;
        OntvangerIds?: string;
        DuurSeconden?: number;
    };
    path?: never;
    query?: never;
    url: '/api/v1/videoboodschappen/uploaden';
};

export type PostApiV1VideoboodschappenUploadenResponses = {
    /**
     * OK
     */
    200: VideoboodschapResponse;
};

export type PostApiV1VideoboodschappenUploadenResponse = PostApiV1VideoboodschappenUploadenResponses[keyof PostApiV1VideoboodschappenUploadenResponses];

export type GetApiV1VideoboodschappenByIdStreamData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/videoboodschappen/{id}/stream';
};

export type GetApiV1VideoboodschappenByIdStreamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1VideoboodschappenByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/videoboodschappen/{id}';
};

export type DeleteApiV1VideoboodschappenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiV1VideoboodschappenByIdData = {
    body?: VideoboodschapUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/videoboodschappen/{id}';
};

export type PatchApiV1VideoboodschappenByIdResponses = {
    /**
     * OK
     */
    200: VideoboodschapResponse;
};

export type PatchApiV1VideoboodschappenByIdResponse = PatchApiV1VideoboodschappenByIdResponses[keyof PatchApiV1VideoboodschappenByIdResponses];

export type PostApiV1VideoboodschappenPreviewData = {
    body?: {
        Bestand: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/videoboodschappen/preview';
};

export type PostApiV1VideoboodschappenPreviewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1VideoboodschappenPreviewByTempIdStreamData = {
    body?: never;
    path: {
        tempId: string;
    };
    query?: never;
    url: '/api/v1/videoboodschappen/preview/{tempId}/stream';
};

export type GetApiV1VideoboodschappenPreviewByTempIdStreamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1VideoboodschappenPreviewByTempIdData = {
    body?: never;
    path: {
        tempId: string;
    };
    query?: never;
    url: '/api/v1/videoboodschappen/preview/{tempId}';
};

export type DeleteApiV1VideoboodschappenPreviewByTempIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1VideoboodschappenVoorErfgenaamByErfgenaamIdData = {
    body?: never;
    path: {
        erfgenaamId: string;
    };
    query?: never;
    url: '/api/v1/videoboodschappen/voor-erfgenaam/{erfgenaamId}';
};

export type GetApiV1VideoboodschappenVoorErfgenaamByErfgenaamIdResponses = {
    /**
     * OK
     */
    200: Array<VideoboodschapResponse>;
};

export type GetApiV1VideoboodschappenVoorErfgenaamByErfgenaamIdResponse = GetApiV1VideoboodschappenVoorErfgenaamByErfgenaamIdResponses[keyof GetApiV1VideoboodschappenVoorErfgenaamByErfgenaamIdResponses];

export type GetApiV1WerkgeverData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/werkgever';
};

export type GetApiV1WerkgeverResponses = {
    /**
     * OK
     */
    200: Array<WerkgeverResponse>;
};

export type GetApiV1WerkgeverResponse = GetApiV1WerkgeverResponses[keyof GetApiV1WerkgeverResponses];

export type PostApiV1WerkgeverData = {
    body?: WerkgeverUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/werkgever';
};

export type PostApiV1WerkgeverResponses = {
    /**
     * OK
     */
    200: WerkgeverResponse;
};

export type PostApiV1WerkgeverResponse = PostApiV1WerkgeverResponses[keyof PostApiV1WerkgeverResponses];

export type DeleteApiV1WerkgeverByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/werkgever/{id}';
};

export type DeleteApiV1WerkgeverByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1WerkgeverByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/werkgever/{id}';
};

export type GetApiV1WerkgeverByIdResponses = {
    /**
     * OK
     */
    200: WerkgeverResponse;
};

export type GetApiV1WerkgeverByIdResponse = GetApiV1WerkgeverByIdResponses[keyof GetApiV1WerkgeverByIdResponses];

export type PutApiV1WerkgeverByIdData = {
    body?: WerkgeverUpsertRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/werkgever/{id}';
};

export type PutApiV1WerkgeverByIdResponses = {
    /**
     * OK
     */
    200: WerkgeverResponse;
};

export type PutApiV1WerkgeverByIdResponse = PutApiV1WerkgeverByIdResponses[keyof PutApiV1WerkgeverByIdResponses];

export type GetApiV1ZoekenData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
    };
    url: '/api/v1/zoeken';
};

export type GetApiV1ZoekenResponses = {
    /**
     * OK
     */
    200: ZoekResultaat;
};

export type GetApiV1ZoekenResponse = GetApiV1ZoekenResponses[keyof GetApiV1ZoekenResponses];
