// <auto-generated />
using System;
using Lumio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lumio.Api.Migrations
{
    [DbContext(typeof(LumioDbContext))]
    [Migration("20260305100420_AddUitvaartContactToEigenaar")]
    partial class AddUitvaartContactToEigenaar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.Bankrekening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("RekeningType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VermogensSoort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("Bankrekeningen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.ErfgenaamToewijzing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ErfgenaamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructies")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.HasIndex("ErfgenaamId");

                    b.ToTable("ErfgenaamToewijzingen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.FysiekBezit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BestemdeErfgenaamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GeschatteWaarde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("KadastraalNummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kenteken")
                        .HasColumnType("TEXT");

                    b.Property<string>("KvKNummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locatie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VermogensSoort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BestemdeErfgenaamId");

                    b.HasIndex("EigenaarId");

                    b.ToTable("FysiekeBezittingen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.Schuld", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BezitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Einddatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("HypotheekVorm")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseMaatschappij")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaandelijkseAflossing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaandelijkseRente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referentie")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Rentepercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Restschuld")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Schuldeiser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchuldeiserEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchuldeiserTelefoon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VermogensSoort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BezitId");

                    b.HasIndex("EigenaarId");

                    b.ToTable("Schulden");
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.Verzekering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Begunstigde")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BegunstigdeErfgenaamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolisNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VermogensSoort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Verzekeraar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerzekeraarEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerzekeraarTelefoon")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VerzekerdBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("Verzekeringen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.ActualisatieBevestiging", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BevestigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domein")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActualisatieBevestigingen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.AfhandelingsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AfgehandeldOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domein")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notitie")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AfhandelingsItems");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.Eigenaar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("BSN")
                        .HasColumnType("TEXT");

                    b.Property<int>("BurgerlijkeStaat")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DatumHuwelijk")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Geboortedatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HuisartsContactId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HuwelijksVoorwaarden")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LegitimatieDatumAfgifte")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LegitimatieGeldigTot")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegitimatieNummer")
                        .HasColumnType("TEXT");

                    b.Property<int>("LegitimatieSoort")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NotarisContactId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnboardingVoltooid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfielFoto")
                        .HasColumnType("BLOB");

                    b.Property<string>("ProfielFotoContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfielFotoNaam")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShamirDrempel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefoon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TijdlijnBekeken")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tussenvoegsel")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UitvaartOndernemerContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HuisartsContactId");

                    b.HasIndex("NotarisContactId");

                    b.HasIndex("UitvaartOndernemerContactId");

                    b.ToTable("Eigenaren");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.Erfgenaam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("BSN")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Geboortedatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HeeftShareOntvangen")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LegitimatieDatumAfgifte")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LegitimatieGeldigTot")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegitimatieNummer")
                        .HasColumnType("TEXT");

                    b.Property<int>("LegitimatieSoort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShareIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ShareUitgegevenOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tussenvoegsel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("Erfgenamen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.Noodcontact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedrijfsNaam")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Functie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructies")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGedeeld")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioriteit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("Noodcontacten");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.SectieNotitie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inhoud")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sectie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("SectieNotities");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.SharedContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedrijfsNaam")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Functie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGedeeld")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relatie")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoon")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("SharedContacts");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.Werkgever", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Afdeling")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedrijfsNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Functietitel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("HrContactEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("HrContactNaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("HrContactTelefoon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsZzp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KvKNummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeidinggevendeEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeidinggevendeNaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeidinggevendeTelefoon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("PensioenfondEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("PensioenfondNaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("PensioenfondTelefoon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartdatumDienstverband")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoonHoofdkantoor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vestigingsplaats")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Werkgevers");
                });

            modelBuilder.Entity("Lumio.Api.Domain.DigitalEstate.CryptoWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("CryptoType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedSeedPhrase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletAdres")
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("CryptoWallets");
                });

            modelBuilder.Entity("Lumio.Api.Domain.DigitalEstate.DigitaalAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAdres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gebruikersnaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("GewensteActie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverdrachtAan")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("DigitaleAccounts");
                });

            modelBuilder.Entity("Lumio.Api.Domain.DigitalEstate.WachtwoordEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedWachtwoord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gebruikersnaam")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("Wachtwoorden");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Documents.PersoonlijkDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<long>("BestandsGrootte")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("BestandsInhoud")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("BestandsNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentGroepId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("VerlooptOp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Versie")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("Documenten");
                });

            modelBuilder.Entity("Lumio.Api.Domain.DonorRegistration.DonorRegistratie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeslisserNaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeslisserRelatie")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeslisserTelefoon")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonorregisterReferentie")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGeregistreerdBijDonorregister")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keuze")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Toelichting")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("DonorRegistraties");
                });

            modelBuilder.Entity("Lumio.Api.Domain.DonorRegistration.OrgaanKeuze", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DonorRegistratieId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orgaan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Toelichting")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WelDoneren")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonorRegistratieId");

                    b.ToTable("OrgaanKeuzes");
                });

            modelBuilder.Entity("Lumio.Api.Domain.EuthanasiaDirective.EuthanasieVoorwaarde", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Toelichting")
                        .HasColumnType("TEXT");

                    b.Property<string>("Voorwaarde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WilsverklaringId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WilsverklaringId");

                    b.ToTable("EuthanasieVoorwaarden");
                });

            modelBuilder.Entity("Lumio.Api.Domain.EuthanasiaDirective.WilsverklaringEuthanasie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("AanvullendeWensen")
                        .HasColumnType("TEXT");

                    b.Property<string>("BehandelVerbod")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DatumOndertekening")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DementieClausule")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DementieClausuleToelichting")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HuisartsContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SituatieBeschrijving")
                        .HasColumnType("TEXT");

                    b.Property<string>("SituatieNotitie")
                        .HasColumnType("TEXT");

                    b.Property<string>("SituatieOpties")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Vertegenwoordiger2ContactId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VertegenwoordigerContactId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WilEuthanasie")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.HasIndex("HuisartsContactId");

                    b.HasIndex("Vertegenwoordiger2ContactId");

                    b.HasIndex("VertegenwoordigerContactId");

                    b.ToTable("Wilsverklaringen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.FuneralWishes.CeremonieDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dresscode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Muziek")
                        .HasColumnType("TEXT");

                    b.Property<string>("Onderdeel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Spreker")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tekstlezing")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UitvaartWensenId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Volgorde")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UitvaartWensenId");

                    b.ToTable("CeremonieDetails");
                });

            modelBuilder.Entity("Lumio.Api.Domain.FuneralWishes.UitvaartGenodigde", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ErfgenaamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NoodcontactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relatie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoon")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UitvaartWensenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UitvaartWensenId");

                    b.ToTable("UitvaartGenodigden");
                });

            modelBuilder.Entity("Lumio.Api.Domain.FuneralWishes.UitvaartWensen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Begraafplaats")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bloemen")
                        .HasColumnType("TEXT");

                    b.Property<string>("BudgetRichting")
                        .HasColumnType("TEXT");

                    b.Property<string>("CeremonieLocatie")
                        .HasColumnType("TEXT");

                    b.Property<string>("CeremonieSoort")
                        .HasColumnType("TEXT");

                    b.Property<string>("Condoleance")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DatumOpgesteld")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HeeftUitvaartVerzekering")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kledingwensen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Muziekwensen")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverigeWensen")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouwadvertentieTekst")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouwkaartTekst")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sprekers")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UitvaartOndernemerContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UitvaartVerzekeringDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoorkeurAulaAdres")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoorkeurAulaNaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoorkeurBegraafplaatsAdres")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoorkeurBegraafplaatsNaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoorkeurCrematoriumAdres")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoorkeurCrematoriumnaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoorkeurType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.HasIndex("UitvaartOndernemerContactId");

                    b.ToTable("UitvaartWensen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Testament.Begunstigde", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ErfgenaamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLegitiemePortie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NoodcontactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoon")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TestamentInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestamentInfoId");

                    b.ToTable("Begunstigden");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Testament.Executeur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bevoegdheden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ErfgenaamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NoodcontactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relatie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoon")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TestamentInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestamentInfoId");

                    b.ToTable("Executeurs");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Testament.TestamentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgemeneWensen")
                        .HasColumnType("TEXT");

                    b.Property<string>("BijzondereBepalingen")
                        .HasColumnType("TEXT");

                    b.Property<string>("CTR_Nummer")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DatumTestament")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Legaten")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NotarisContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestamentLocatie")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestamentType")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("UitsluitingsClausule")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.HasIndex("NotarisContactId");

                    b.ToTable("Testamenten");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Testament.TestamentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notitie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TestamentInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Versie")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestamentInfoId");

                    b.ToTable("TestamentSnapshots");
                });

            modelBuilder.Entity("Lumio.Api.Domain.VideoMessages.Videoboodschap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("TEXT");

                    b.Property<long>("BestandsGrootte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BestandsNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BestandsPad")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuurSeconden")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EigenaarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EigenaarId");

                    b.ToTable("Videoboodschappen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.VideoMessages.VideoboodschapBlob", b =>
                {
                    b.Property<Guid>("VideoboodschapId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Inhoud")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("VideoboodschapId");

                    b.ToTable("VideoboodschapBlobs");
                });

            modelBuilder.Entity("Lumio.Api.Domain.VideoMessages.VideoboodschapOntvanger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ErfgenaamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GewijzigdOp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoboodschapId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VideoboodschapId");

                    b.ToTable("VideoboodschapOntvangers");
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.Bankrekening", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.ErfgenaamToewijzing", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumio.Api.Domain.Common.Erfgenaam", "Erfgenaam")
                        .WithMany()
                        .HasForeignKey("ErfgenaamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Erfgenaam");
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.FysiekBezit", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Erfgenaam", "BestemdeErfgenaam")
                        .WithMany()
                        .HasForeignKey("BestemdeErfgenaamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BestemdeErfgenaam");
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.Schuld", b =>
                {
                    b.HasOne("Lumio.Api.Domain.AssetRegistry.FysiekBezit", "Bezit")
                        .WithMany("LinkedSchulden")
                        .HasForeignKey("BezitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bezit");
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.Verzekering", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.Eigenaar", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.SharedContact", "HuisartsContact")
                        .WithMany()
                        .HasForeignKey("HuisartsContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lumio.Api.Domain.Common.SharedContact", "NotarisContact")
                        .WithMany()
                        .HasForeignKey("NotarisContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lumio.Api.Domain.Common.SharedContact", "UitvaartOndernemerContact")
                        .WithMany()
                        .HasForeignKey("UitvaartOndernemerContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HuisartsContact");

                    b.Navigation("NotarisContact");

                    b.Navigation("UitvaartOndernemerContact");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.Erfgenaam", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", "Eigenaar")
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eigenaar");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.Noodcontact", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.SectieNotitie", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.Common.SharedContact", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", "Eigenaar")
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eigenaar");
                });

            modelBuilder.Entity("Lumio.Api.Domain.DigitalEstate.CryptoWallet", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.DigitalEstate.DigitaalAccount", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.DigitalEstate.WachtwoordEntry", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.Documents.PersoonlijkDocument", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.DonorRegistration.DonorRegistratie", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", "Eigenaar")
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eigenaar");
                });

            modelBuilder.Entity("Lumio.Api.Domain.DonorRegistration.OrgaanKeuze", b =>
                {
                    b.HasOne("Lumio.Api.Domain.DonorRegistration.DonorRegistratie", "DonorRegistratie")
                        .WithMany("OrgaanKeuzes")
                        .HasForeignKey("DonorRegistratieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonorRegistratie");
                });

            modelBuilder.Entity("Lumio.Api.Domain.EuthanasiaDirective.EuthanasieVoorwaarde", b =>
                {
                    b.HasOne("Lumio.Api.Domain.EuthanasiaDirective.WilsverklaringEuthanasie", "Wilsverklaring")
                        .WithMany("Voorwaarden")
                        .HasForeignKey("WilsverklaringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wilsverklaring");
                });

            modelBuilder.Entity("Lumio.Api.Domain.EuthanasiaDirective.WilsverklaringEuthanasie", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", "Eigenaar")
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumio.Api.Domain.Common.SharedContact", "HuisartsContact")
                        .WithMany()
                        .HasForeignKey("HuisartsContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lumio.Api.Domain.Common.SharedContact", "Vertegenwoordiger2Contact")
                        .WithMany()
                        .HasForeignKey("Vertegenwoordiger2ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lumio.Api.Domain.Common.SharedContact", "VertegenwoordigerContact")
                        .WithMany()
                        .HasForeignKey("VertegenwoordigerContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eigenaar");

                    b.Navigation("HuisartsContact");

                    b.Navigation("Vertegenwoordiger2Contact");

                    b.Navigation("VertegenwoordigerContact");
                });

            modelBuilder.Entity("Lumio.Api.Domain.FuneralWishes.CeremonieDetail", b =>
                {
                    b.HasOne("Lumio.Api.Domain.FuneralWishes.UitvaartWensen", "UitvaartWensen")
                        .WithMany("CeremonieDetails")
                        .HasForeignKey("UitvaartWensenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UitvaartWensen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.FuneralWishes.UitvaartGenodigde", b =>
                {
                    b.HasOne("Lumio.Api.Domain.FuneralWishes.UitvaartWensen", "UitvaartWensen")
                        .WithMany("Genodigden")
                        .HasForeignKey("UitvaartWensenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UitvaartWensen");
                });

            modelBuilder.Entity("Lumio.Api.Domain.FuneralWishes.UitvaartWensen", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", "Eigenaar")
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumio.Api.Domain.Common.SharedContact", "UitvaartOndernemerContact")
                        .WithMany()
                        .HasForeignKey("UitvaartOndernemerContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eigenaar");

                    b.Navigation("UitvaartOndernemerContact");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Testament.Begunstigde", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Testament.TestamentInfo", "TestamentInfo")
                        .WithMany("Begunstigden")
                        .HasForeignKey("TestamentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestamentInfo");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Testament.Executeur", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Testament.TestamentInfo", "TestamentInfo")
                        .WithMany("Executeurs")
                        .HasForeignKey("TestamentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestamentInfo");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Testament.TestamentInfo", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", "Eigenaar")
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumio.Api.Domain.Common.SharedContact", "NotarisContact")
                        .WithMany()
                        .HasForeignKey("NotarisContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eigenaar");

                    b.Navigation("NotarisContact");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Testament.TestamentSnapshot", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Testament.TestamentInfo", "TestamentInfo")
                        .WithMany("Snapshots")
                        .HasForeignKey("TestamentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestamentInfo");
                });

            modelBuilder.Entity("Lumio.Api.Domain.VideoMessages.Videoboodschap", b =>
                {
                    b.HasOne("Lumio.Api.Domain.Common.Eigenaar", null)
                        .WithMany()
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.VideoMessages.VideoboodschapBlob", b =>
                {
                    b.HasOne("Lumio.Api.Domain.VideoMessages.Videoboodschap", null)
                        .WithOne("Blob")
                        .HasForeignKey("Lumio.Api.Domain.VideoMessages.VideoboodschapBlob", "VideoboodschapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumio.Api.Domain.VideoMessages.VideoboodschapOntvanger", b =>
                {
                    b.HasOne("Lumio.Api.Domain.VideoMessages.Videoboodschap", "Videoboodschap")
                        .WithMany("Ontvangers")
                        .HasForeignKey("VideoboodschapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Videoboodschap");
                });

            modelBuilder.Entity("Lumio.Api.Domain.AssetRegistry.FysiekBezit", b =>
                {
                    b.Navigation("LinkedSchulden");
                });

            modelBuilder.Entity("Lumio.Api.Domain.DonorRegistration.DonorRegistratie", b =>
                {
                    b.Navigation("OrgaanKeuzes");
                });

            modelBuilder.Entity("Lumio.Api.Domain.EuthanasiaDirective.WilsverklaringEuthanasie", b =>
                {
                    b.Navigation("Voorwaarden");
                });

            modelBuilder.Entity("Lumio.Api.Domain.FuneralWishes.UitvaartWensen", b =>
                {
                    b.Navigation("CeremonieDetails");

                    b.Navigation("Genodigden");
                });

            modelBuilder.Entity("Lumio.Api.Domain.Testament.TestamentInfo", b =>
                {
                    b.Navigation("Begunstigden");

                    b.Navigation("Executeurs");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Lumio.Api.Domain.VideoMessages.Videoboodschap", b =>
                {
                    b.Navigation("Blob");

                    b.Navigation("Ontvangers");
                });
#pragma warning restore 612, 618
        }
    }
}
