import { defineConfig } from "@hey-api/openapi-ts";

export default defineConfig({
  client: "@hey-api/client-fetch",
  // SP-1-004: use the committed spec file (generated by npm run export-spec).
  // Run against the live server only when regenerating: input: "http://127.0.0.1:5123/swagger/v1/swagger.json"
  input: "openapi.json",
  output: {
    path: "src/lib/api",
    format: "prettier",
  },
});
