namespace Lumio.Api.Dtos.Common;

public record WerkgeverResponse(
    Guid Id,
    string BedrijfsNaam,
    string? KvKNummer,
    string? Adres,
    string? Postcode,
    string? Vestigingsplaats,
    string? Website,
    string? TelefoonHoofdkantoor,
    string? Functietitel,
    string? Afdeling,
    DateOnly? StartdatumDienstverband,
    bool IsZzp,
    string? PensioenfondNaam,
    string? PensioenfondTelefoon,
    string? PensioenfondEmail,
    string? HrContactNaam,
    string? HrContactTelefoon,
    string? HrContactEmail,
    string? LeidinggevendeNaam,
    string? LeidinggevendeTelefoon,
    string? LeidinggevendeEmail,
    string? Notities);

public record WerkgeverUpsertRequest(
    string BedrijfsNaam,
    string? KvKNummer,
    string? Adres,
    string? Postcode,
    string? Vestigingsplaats,
    string? Website,
    string? TelefoonHoofdkantoor,
    string? Functietitel,
    string? Afdeling,
    DateOnly? StartdatumDienstverband,
    bool IsZzp,
    string? PensioenfondNaam,
    string? PensioenfondTelefoon,
    string? PensioenfondEmail,
    string? HrContactNaam,
    string? HrContactTelefoon,
    string? HrContactEmail,
    string? LeidinggevendeNaam,
    string? LeidinggevendeTelefoon,
    string? LeidinggevendeEmail,
    string? Notities);
