/**
 * build-icons.mjs
 *
 * Converts build/source/icon.svg → all platform icon formats:
 *   build/icon.ico        (Windows: multi-resolution 16–256 px)
 *   build/icon.icns       (macOS: generated by electron-icon-builder)
 *   build/icons/*.png     (Linux: 16, 32, 48, 64, 128, 256, 512, 1024 px)
 *   build/source/icon.png (1024×1024 master PNG, used by electron-icon-builder)
 *
 * Usage:  npm run build:icons
 *
 * Requires: sharp, electron-icon-builder (both are devDependencies)
 */

import { createRequire } from 'module';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';
import { spawnSync } from 'child_process';

const require = createRequire(import.meta.url);
const sharp = require('sharp');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const svgInput = path.join(root, 'build', 'source', 'icon.svg');
const masterPng = path.join(root, 'build', 'source', 'icon.png');
const iconsDir = path.join(root, 'build', 'icons');

// ── Step 1: SVG → 1024×1024 master PNG ──────────────────────────────────────
// libvips (used by sharp) is strict about XML: <!-- comments containing -- are
// invalid. Strip all XML comments from the SVG before passing it to sharp.
console.log('[icons] Converting SVG → master PNG (1024×1024)…');
const svgRaw = fs.readFileSync(svgInput, 'utf8');
const svgClean = Buffer.from(svgRaw.replace(/<!--[\s\S]*?-->/g, ''));

await sharp(svgClean)
  .resize(1024, 1024)
  .png()
  .toFile(masterPng);
console.log(`[icons] Written: ${masterPng}`);

// ── Step 2: Master PNG → Linux PNG set ───────────────────────────────────────
const linuxSizes = [16, 32, 48, 64, 128, 256, 512, 1024];
fs.mkdirSync(iconsDir, { recursive: true });

console.log('[icons] Generating Linux PNG set…');
await Promise.all(
  linuxSizes.map(async (size) => {
    const dest = path.join(iconsDir, `${size}.png`);
    await sharp(masterPng).resize(size, size).png().toFile(dest);
    console.log(`[icons]   ${dest}`);
  })
);

// ── Step 3: electron-icon-builder → ICO + ICNS ───────────────────────────────
// electron-icon-builder is a CLI tool; invoke it via spawnSync with shell:true
// so .cmd wrappers work on Windows. It writes to {output}/icons/ with --flatten.
console.log('[icons] Running electron-icon-builder (ICO + ICNS)…');

const builderBin = path.join(root, 'node_modules', '.bin', 'electron-icon-builder');
const result = spawnSync(
  builderBin,
  ['--input', masterPng, '--output', path.join(root, 'build'), '--flatten'],
  { stdio: 'inherit', shell: true, cwd: root }
);
if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

// electron-icon-builder writes icon.ico + icon.icns into {output}/icons/ with --flatten.
// electron-builder.yml expects build/icon.ico + build/icon.icns (one level up).
// Copy them to the expected locations.
const builtIco = path.join(root, 'build', 'icons', 'icon.ico');
const builtIcns = path.join(root, 'build', 'icons', 'icon.icns');

if (fs.existsSync(builtIco)) {
  fs.copyFileSync(builtIco, path.join(root, 'build', 'icon.ico'));
  console.log('[icons]   build/icon.ico');
}
if (fs.existsSync(builtIcns)) {
  fs.copyFileSync(builtIcns, path.join(root, 'build', 'icon.icns'));
  console.log('[icons]   build/icon.icns');
}

// Also rename the Linux PNGs back to plain {size}.png format for our build/icons/
// (electron-icon-builder renames them to {size}x{size}.png; we want plain {size}.png)
for (const size of linuxSizes) {
  const sizeX = path.join(iconsDir, `${size}x${size}.png`);
  const plain  = path.join(iconsDir, `${size}.png`);
  if (fs.existsSync(sizeX) && !fs.existsSync(plain)) {
    fs.copyFileSync(sizeX, plain);
  }
}

// ── Step 4: Taskbar overlay icons (Windows, 16×16) ──────────────────────────
// Small status indicators shown on the app's taskbar button (EL-5-06).
console.log('[icons] Generating taskbar overlay icons…');

const overlaySvgs = {
  'overlay-ok.png': Buffer.from(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">'
    + '<circle cx="8" cy="8" r="8" fill="#22c55e"/>'
    + '<path d="M4 8l3 3 5-5" stroke="#fff" stroke-width="2" stroke-linecap="round" fill="none"/>'
    + '</svg>'
  ),
  'overlay-warn.png': Buffer.from(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">'
    + '<circle cx="8" cy="8" r="8" fill="#f59e0b"/>'
    + '<path d="M8 4v5" stroke="#fff" stroke-width="2" stroke-linecap="round"/>'
    + '<circle cx="8" cy="11.5" r="1" fill="#fff"/>'
    + '</svg>'
  ),
};

await Promise.all(
  Object.entries(overlaySvgs).map(async ([filename, svgBuf]) => {
    const dest = path.join(root, 'build', filename);
    await sharp(svgBuf).resize(16, 16).png().toFile(dest);
    console.log(`[icons]   build/${filename}`);
  })
);

console.log('[icons] Done. Output:');
console.log('[icons]   build/icon.ico');
console.log('[icons]   build/icon.icns');
console.log('[icons]   build/icons/{size}.png');
console.log('[icons]   build/overlay-ok.png');
console.log('[icons]   build/overlay-warn.png');
