/**
 * Auto-generated help content embedded at build time.
 * Source: docs/user-manual/{NL,EN}/*.md
 *
 * DO NOT EDIT MANUALLY - regenerate with: node scripts/generate-help-content.js
 * This file is auto-regenerated by the "predev" and "prebuild" npm scripts.
 */

export type HelpLocale = "nl" | "en";

const helpContent: Record<HelpLocale, Record<string, string>> = {
  nl: {
  },
  en: {
  },
};

/**
 * Get embedded help markdown content for a chapter file and locale.
 * Returns undefined if not found.
 */
export function getHelpContent(
  filename: string,
  locale: string,
): string | undefined {
  const loc = (locale === "en" ? "en" : "nl") as HelpLocale;
  return helpContent[loc]?.[filename];
}
